General/redhat-machines-report-they-are-not-registered-to-rhn-when-running-yum.md

Set "contentIsHTML": false to properly reflect the markdown for "RedHat machines report they are not registered to RHN when running 'yum'"

"contentIsHTML": false

---

Managed Services/managed-operating-system-frequently-asked-questions.md

The links as they were were going to password-protected ctl.io pages that referenced the new URL for the targets.  I put the new URLs in place.

fixing URLs to use www.centurylinkcloud.com and https

---

Ecosystem Partners/ecosystem-partner-list.md

Fixed typo caught by Chris Little in Slack.

MongoDB link missing .md extension

---

Managed Services/troubleshooting-a-failed-managed-services-blueprint.md

Added information to explain why Make managed RHEL BPs will fail the
same hour out of every week.

Updated Troubleshooting Failed Managed Blueprint

---

AppFog/Legacy Version 1/installing-the-af-cli-tool-on-mac-os-x.md

Updated to recommend using Ruby version 2.0 instead of 2.1

Update installing-the-af-cli-tool-on-mac-os-x.md- change Ruby version from 2.1 to 2.0

---

Object Storage/introducing-object-storage.md

The list was referencing buckets in two sections where it should have
referenced objects.

Correcting the list

---

Support/ticket-prioritization-matrix.md

We needed to specify that developer support for Normal tickets are under an 8 hour SLA.

Developer Support exception

---

WordPress/wordpress-cloudflare-SSL-configuration.md

This addition is to show how a client can use CloudFlare for SSL Termination for custom hostnames.

Adding KB Article for CloudFlare SSL Termination

---

Servers/self-service-vm-import-ovf-requirements.md

We need to add an additional requirement for Linux to ensure proper functionality after they import their Redhat OVF's.

Self-Service-VM-Import-Linux-Reqs

---

Network/centurylink-cloud-network-load-balancing-health-check-services.md

The correct technical term is HTTP-ECV, not EVC.

Network LB health checks- EVC to ECV

---

WordPress/getting-started-with-wordpress-as-a-service.md
WordPress/wordpress-deployment-rollback.md

We are adding the ability for customers to quickly roll back pushes of bad changes to their WordPress sites.

Documenting WordPress deployment rollback feature for customers

---

AppFog/using-ctl-mysql-with-appfog-apps.md

We got rid of the “free” plan in AppFog and replaced it with the term
“micro”.  Updating this KB article to reflect that change.

Using DBaaS with AppFog KB Update

---

Disaster Recovery/safehaven-configure-email-alerts.md
Disaster Recovery/safehaven-gracefully-shutdown-srn.md
Disaster Recovery/safehaven-manually-removing-stuck-test-failover-clones.md

fixed typo in SAHA email config relay@t3.mx changed to relay.t3.mx,
added connecting to smtp relay content

SafeHaven Email Config typo fix

---

Object Storage/introducing-object-storage.md

The maximum size of an object our service supports is 5 TB and not 6 TB.
I'm updating this KB article to reflect that.

Correcting max object size amount

---

Managed Services/managed-operating-system-frequently-asked-questions.md
Managed Services/what-happens-when-windows-servers-are-made-managed.md
Servers/patching-as-a-service.md

Patching as a Service: 1) Let users know they can remove DNS after
execution per https://t3n.zendesk.com/agent/tickets/1205421 2) Let
Users know they can create noc tickets
Managed OS: 1) Specified that buys can contact sales about Advanced
Solutions 2) Specified that if D-drive already exists, make-managed
will just create the next, unused letter drive. Both per
https://t3n.zendesk.com/agent/tickets/1190527

Updates to Patch-aaS and Managed OS FAQ

---

WordPress/cherry_framework.md
WordPress/getting-started-with-wordpress-as-a-service.md
WordPress/wordPress-site-updates-with-git.md
WordPress/wordpress-SMTP-Configuration.md
WordPress/wordpress-cloudflare-SSL-configuration.md
WordPress/wordpress-custom-domain-configuration.md
WordPress/wordpress-database-access-with-external-tools.md
WordPress/wordpress-deployment-rollback.md
WordPress/wordpress-git-installation.md
WordPress/wordpress-git-repository-password-caching.md
WordPress/wordpress-git-ssh.md
WordPress/wordpress-known-limitations.md
WordPress/wordpress-local-development.md
WordPress/wordpress-persistent-storage-configuration.md
WordPress/wordpress-plugin-installation.md
WordPress/wordpress-seo.md
WordPress/wordpress-site-migration-to-centurylink-cloud.md
WordPress/wordpress-technical-specifications.md
WordPress/wordpress-updating-core.md
WordPress/wordpress_woocommerce.md

Cannot have WordPress-As-A-Service as a product name because of
trademark issues. Currently will not have a product name, will make the
following statements: CenturyLink WordPress Hosting/CenturyLink
WordPress Hosting Platform.

Product Name Change

---

Managed Services/what-happens-when-windows-servers-are-made-managed.md

Untrue: operationally expected updates are installed, bringing the
server to a Centurylink-approved patch level.
True: Vendor-approved patches are installed at the initial, make-managed step.

Updated Info About Vendor-Approved Patches

---

Object Storage/using-object-storage-with-a-cloud-storage-gateway.md

There were links pointing to outdated KB articles.  I have changed these to point to the new KB articles.

Changing links to point to new KB articles

---

Network/dedicated-load-balancer-basic-management.md

Updated the links for:
in section Prerequisites, bullets 3 and 4 have links to internal (and obsolete) KBs:
https://support.ctl.io/hc/en-us/articles/204531055-Load-Balancing-Dedicated-vs-Shared
https://t3n.zendesk.com/entries/23688917-Load-Balancing-Dedicated-vs-Shared
TO
https://www.ctl.io/knowledge-base/network/load-balancing-dedicated-vs-shared/
https://www.ctl.io/knowledge-base/general/how-to-configure-java-settings-to-access-web-user-interfaces/

Updated dedicated-load-balancer-basic-management

---

Object Storage/s3cmd-object-storage-management-for-linux-machines.md

This was discovered by a customer who copy pasted our .s3cfg file.  Whoever created it initially had a local proxy setup which no customers will actually use.

removed proxy config so no proxy is used

---

Disaster Recovery/build-safehaven-base-image-template-from-ubuntu.md

fix typo in title for SH template creation- it used to read "imaage"

fix typo in title for SH template creation

---

Object Storage/using-object-storage-from-3rd-party-tools.md

The newer versions of Cloudberry support ACL changes when using the
CenturyLink account type.  So I'm removing this line.

Cloudberry supports ACLs on the CTL account

---

Object Storage/object-storage-regions-and-service-points.md

Instead of marking the data centers as primary/secondary, I added columns for primary/secondary.  This is a much cleaner look.

Changing how the table displays information

---

Accounts & Users/role-permissions-matrix.md

per may 24th release, included Anti-Affinity as well since this was missed
Minor change to the Server Operator role in Control. The Server Operator role now has the ability to CREATE, EDIT and DELETE Vertical Autoscale, Horizontal Autoscale, and Alert Policies in Control (previously, it was VIEW only). This is a minor change which has no impact on cost or other features within the Control Portal.

update roles matrix per may 24th release

---

Release Notes/2016-05-24-cloud-platform-release-notes.md

Recreate the 2016-05-24-cloud-platform-release-notes file that was overwritten by the 6/7/16 release notes.

re-Create 2016-05-24-cloud-platform-release-notes.md

---

Servers/how-to-clone-a-virtual-machine-os-instance.md

Added third bullet point to inform customer that snapshots on VMs will cause the clone process to fail.
Added text:
"Before attempting to clone a virtual machine, all snapshots must be removed.  A virtual machine with an active snapshot will fail the clone process."
Related to Customer Care PM:
https://t3n.zendesk.com/agent/tickets/1282410

UPDATE - Add exclusion for snapshots

---

Support/purchasing-service-engineering-packages.md

Change this line:
This primary point of contact will works a specified shift based on the Customer’s needs.
To:
This primary point of contact will work a specified shift based on the Customer’s needs.

Corrected typo from works to work

---

Managed Services/managed-operating-system-frequently-asked-questions.md

A brief outline of the internal networks necessary for a server to be able to connect to when converting a server to Managed, some steps to try if there is an issue with the blueprint that appears to be network related, and called out how custom CNS configurations can affect the process.

Added section for Network Requirements.

---

Object Storage/using-object-storage-via-rest-api-aws-sdk.md

The `aws-sdk` package for NodeJS was updated to default to V4 signatures for S3. Object Storage requires V2 signatures. This PR updates the NodeJS example to reflect that.

Update Node Object Storage example to work with latest aws-sdk lib.

---

Object Storage/using-object-storage-from-the-control-portal.md

Updating the document to reflect that we no longer allow dots in the name of buckets.

Updating because we no longer allow dots in names

---

Ecosystem Partners/Marketplace Guides/getting-started-with-chyrp-blueprint.md

Received a report from www.whoishostingthis.com about the linked homepage being down. According to the their Chyrp page (http://www.whoishostingthis.com/resources/chyrp), it's been down since September 2015. Re-linked to their GitHub repo (https://github.com/chyrp/chyrp).

Broken Link Update - Chyrp Homepage

---

Network/creating-cross-data-center-firewall-policies.md

Create network vlan's link now points to the public KB and not one housed within Zendesk.  Updated some language in the KB, and the date and author is now omitted

Fixed link to point to external KB and updates

---

Support/how-to-check-priority-level-of-your-tickets.md

added Status and Priority, and made accurate for current functionaility in the ZenDesk portal for non-agent accounts to view support tickets

Updated for accuracy, included Status

---

Control Portal/understang-cost estimates in control.md

Current hour does not contain MSSQL license anymore due to the new
monthly cycle

Update the cost estimate to reflect the new MSSQL billing model

---

Network/creating-a-self-service-ipsec-site-to-site-vpn-tunnel.md

https://t3n.zendesk.com/agent/tickets/1332124
Added the following to Step 5:
"Please note that the 172.17.1.0/24 network is in use by CLC for management purposes and should not be used as a remote network. If your remote networks conflict with the CLC customer network blocks in use for the specified datacenter then your VPN becomes a Non-standard configuration that will require NAT. You can email help@ctl.io for a list of CLC customer network blocks for a specified datacenter."

Added notes to Step 5 about CLC reserved networks

---

Blueprints/deploy-microsoft-sql-server-using-blueprint.md

Added below line to the General Notes section:
"To remove the SQL license from your server, it must be deleted. Customers are responsible for migrating their data prior to deleting the server. Microsoft will not accept license termination unless the VM is fully removed."

Removing the SQL license from the server

---

Servers/self-service-vm-import-ovf-requirements.md

Changed our VMX version requirement from 11 to 8. While we believe the platform supports vmx hardware version up to this level, we have not tested it for self service imports yet.

Correct VMX version

---

Servers/self-service-vm-import-ovf-requirements.md

Added note for RHEL7 servers requiring "Consistent Network Device Naming" to be enabled for successful import.

RHEL7 Consistent Network Setting

---

Release Notes/2018/2018-04-10-cloud-platform-release-notes.md

updated to reflect previous release model, we should not put pricing in release notes as it causes problems if pricing changes. simply link to pricing pages.

updated to reflect previous release model

---

Network/network-exchange-clc-managed-hosting-endpoint-guide.md

this was originally misleading. It should be Managed Hosting via HAN. appropriate updates made.

Reworded to be Managed Hosting via HAN

---

Cloud Application Manager/Automating Deployments/running-code-outside-an-instance.md

The code formatting with "sh" does not use syntax highlighting and is more
difficult to read than with default style.

Escape jinja syntax in example code block and use default style.

---

Object Storage/object-storage-user-management.md

When a user becomes disabled, its buckets and objects are still accessible, just not by that user.

Change wording around disabling OS users.

---

Object Storage/object-storage-regions-and-service-points.md

We don't want to explicitly call out individual datacenters when referring to object storage. The only things users need to know about in order to use object storage are the regions.

Remove datacenters from region endpoint table.

---

Managed Services/managed-operating-system-frequently-asked-questions.md

In "How can I tell my managed VMs from my unmanaged VMs in the CenturyLink Cloud Control portal?" it should be a CenturyLink logo rather than an asterisks that denotes a Managed server.

Changed managed servers prefix - asterisk to logo

---

Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md

AWS Hardening document referenced by CAM Roles, <https://www.ctl.io/knowledge-base/cloud-application-manager/cloud-optimization/partner-cloud-integration-aws-hardening-permissions/>, has several issues.
1. Does not actually give the names of the roles. It's not very useful to refer to the URL in the description of muiltiple roles if there is no actual occurrence of the role name in the linked page. 
2. Line "Centurylink Operations Role" should be more green and less indented to identify it as the beginning of a section on a new role rather a continuation of the "Customer Role" Section.

Update per Operations

---

Servers/resizing-disks-in-linux-virtual-machines.md

Changed (../Servers/manually-expanding-file-system-on-linux-machines.md#part-3-moving-and-expanding-drives-on-older-partitioned-images)
to 
(../Servers/manually-expanding-file-system-on-linux-machines#part-3-moving-and-expanding-drives-on-older-partitioned-images)

fixing broken link

---

Servers/server-comparison-matrix.md

Another data point to publicly state Blueprint functionality is not supported for Bare Metal servers.

Adding section for Blueprints

---

Servers/resizing-disks-in-linux-virtual-machines.md

Fixing the dead link to performing the expansion in Linux, which is at the end of this article.
https://t3n.zendesk.com/agent/tickets/1593229

Fixed dead link at end of article

---

Servers/extending-windows-disks-on-centurylink-cloud.md

It has been identified that the OS names listed under Prerequisites are incorrect OS names. Correct OS names are: "Windows Server 2008 R2", "Windows Server 2012", ''Windows Server 2012 R2", ''Windows Server 2016". Note that 2012R2 and 2016 were missing in the KB.

Update to "Extending Windows Disks on CenturyLink Cloud" KB

---

Servers/cloning-best-practices.md

To include advisory on keeping VMWare Tools updated on source servers to help avoid a known issue. Blueprints have been known to fail due to a version mismatch between the source server and what the platform expects during the validation phase, which is usually the latest available update.

Update cloning best practices kb

---

Network/troubleshooting-potential-network-performance-issues-with-winmtr.md

We removed the reference to http://winmtr.net/download-winmtr/ as it was found to be down. Customers will have to search for the utility and download from a trusted source.

Remove dead link

---

Cloud Application Manager/Analytics/CloudApplicationManagerAnalyticsUI.md

* After you activate Analytics for providers for which you pay the vendor directly, CenturyLink will read your Provider's charges in our calculation of Platform Advisory Support
* For AWS, these are the scenarios where Analytics can provide cost and usage data: 1) accounts which are not members of AWS Organizations 2) accounts which are members of AWS organizations and the CAM admin has also set up an Analyzed provider for the Master Payer of that organization. 
* In the second scenario above, CAM will read usage for the entire organization and apply that to Platform Advisory Support even if all the accounts in the organization have not all been associated to CAM Providers.
* For AWS scenarios where Analytics does not see cost and usage data, it will still offer features including …

Analytics Update

---

Network/network-access-options-for-connecting-to-centurylink-clouds-platform.md

Removed the bullet point "Customers who have applications hosted in CenturyLink datacenters, running on the value-added service network known as the Hosted Area Network (HAN) also have the option of buying a managed link into the cloud that bypasses the Internet. This product is known as Cloud Network Service (CNS) and it can be ordered by contacting your CenturyLink account executive."
https://ctliotest.atlassian.net/browse/PE-2080

Remove CNS Reference

---

Servers/redhat-machines-report-they-are-not-registered-to-rhn-when-running-yum.md

We do not want customers to bring their own license because there is no process that stops them from being double billed.  Until we have a feature and multiple customer want this then we will add a new KB regarding this.

Remove BYOL instructions

---

Cloud Application Manager/Automating Deployments/running-code-outside-an-instance.md

@gsanchezu I've verified that python3 is the only one available. And it's working properly, so we need to update this accordingly.

Fix python3 shebang and and python3 in available languages

---

General/CenturyLinkCloud/centurylink-cloud-data-center-locations.md

From "Peer 1 Hosting" to "Aptum" to reflect last year's re-branding.

Update CA2 provider

---

Backup/simple-backup-service-faqs.md

The below content added to the first Question in the KB. 
SBS Requires SFTP to Install Client Packages. Sftp service should be enabled on Linux Servers.
- To Enable sftp service on LInux Servers, 
1. Edit SSH configuration file /etc/ssh/sshd_config and add the below line
```
Subsystem sftp /usr/libexec/openssh/sftp-server
```
2. save the file and restart sftp service to the changes take effect.
```
service sshd restart

SBS Requires SFTP to Install Client Packages

---

Accounts & Users/closing-an-account.md

"Close Account" link in control is not reliable. 
It creates a poor customer experience to think that the user has done everything necessary to request account closure when in fact no ticket was generated from the click.
So updating the Public KB to guide the customer to manually send an email to help@ctl.io or submit a separate ticket to request the account to be closed.

"Close Account" link in control is not reliable

---

General/Authentication/lumen-master-account-common-issues-and-frequently-asked-questions.md

The CRC is now enabled with admin access to support all matters formerly designated to the Public Cloud Customer Care team. Support has transferred to CRC.

all support to client response center

---

Edge Computing Solutions/Getting Started/bare-metal-server-failures.md

Removed the phrasing "If there's no data that needs to be recovered" because it implies that we can assist with recovering data.  
Data backup and recovery is the customer's responsibility and is outside the scope of support for the Edge Bare Metal product. In the case of critical hardware failure, we recommend reprovisioning new hardware as we will 'not' attempt to recover the current bare metal server.

Edited the **Resolution of Full Failure** section for clarity

---

Support/how-do-i-report-a-support-issue.md

corrected image file calls in https://www.ctl.io/knowledge-base/support/how-do-i-report-a-support-issue/ MD file, changed "lumen" to "centurylink" because image files were designated as such

EDGEC-127_missing-images

---

Blueprints/deploy-microsoft-sql-server-using-blueprint.md

Runner was deprecated in 2020 and is no longer available.

Removing references to Runner

---

Servers/bare-metal-faq.md

Runner was deprecated in 2020 and is no longer available. All references to it were removed.

Removed references to Runner

---

Servers/creating-and-managing-server-snapshots.md

Runner was deprecated in 2020 and is no longer available. Removed references to using Runner to schedule snapshots.

Removed reference to Runner

---

index.md

Runner was deprecated in 2020 and is no longer available.

Removed Runner
