- Ecosystem Partners/centurylink-cloud-ecosystem-program-guide.md
Updated Feb 17 edits that did not make the content sync.
Updated new KB link inside document.
> Updated Program Guide

- Servers/server-naming-convention.md
Update server-naming-convention.md for correct Account Alias character limits. (2-4)
> Alias Update on server-naming-convention.md

- Blueprints/understanding-the-difference-between-templates-blueprints-and-packages.md
Added reference to Partner Templates
> Edited BP Article

- Ecosystem Partners/getting-started-with-pivotal-greenplum-blueprint.md
Minor edits to language and phrasing.
> Edited Greenplum KB

- Ecosystem Partners/How To Publish a Partner Template from a Virtual Appliance.md
> Updated the pricing information for Eco Partners

- Managed Services/managed-backup-frequently-asked-questions.md
> Added 3 new FAQs

- Blueprints/centurylink-cloud-public-blueprint-packages.md
- General/consuming-webhook-alerts-with-3rd-party-web-apps.md
Changed Date on KB for write up of instructions for broader team to get
screen cap
> Change Date

- Ecosystem Partners/getting-started-with-a10-vthunder-partner-template.md
- Ecosystem Partners/getting-started-with-vormetric-dsm.md
Vormetric changes - please approve and publish
> Bob stolzberg test

- Servers/hyperscale-server-faq.md
fixed Hyperscale FAQ formatting
> fixed Hyperscale FAQ formatting

- Ecosystem Partners/getting-started-with-a10-vthunder-partner-template.md
Had to fix a # to Number so formatting didn’t break.
> Small Formatting change

- Autoscale/autoscale-faq.md
> RHEL 7 added to notes on faq

- Servers/hyperscale-server-faq.md
Hyperscale FAQ list stated 5 ways its unique, but only 4 items were listed.  updated to reflect 4
> Hyperscale FAQ Typo

- Ecosystem Partners/getting-started-with-cohesiveft-vns3-partner-template.md
> New KB article for CohesiveFT VNS3 partner template

- Servers/securing-windows-remote-desktop-services-aka-rds-rdp-andor-rpc.md
Added additional information the KB article I wrote a couple years ago.
Dave
> KB Update: Securing Windows Remote Desktop Services (aka RDS, RDP, and/or RPC)

- Managed Services/getting-started-with-cloudera-on-centurylink-cloud.md
- Managed Services/getting-started-with-managed-active-directory.md
- Managed Services/getting-started-with-managed-apache.md
- Managed Services/getting-started-with-managed-microsoft-iis.md
- Managed Services/getting-started-with-managed-microsoft-sql-server.md
- Managed Services/getting-started-with-managed-mysql-replication.md
- Managed Services/getting-started-with-managed-mysql.md
- Managed Services/getting-started-with-managed-tomcat.md
- Managed Services/managed-backup-frequently-asked-questions.md
- Managed Services/managed-operating-system-frequently-asked-questions.md
> new faq in managed backup

- Ecosystem Partners/getting-started-with-minecraft-server-blueprint.md
Getting started with Minecraft Server Blueprint.  We’re gonna make some
money on this one!
> New Minecraft Server Blueprint Doc

- Ecosystem Partners/getting-started-with-mongodb-blueprint.md
Fixed MongoDB typo in the Overview section and edited phrasing in a few
areas.
> Fixed Typo, Tuned Language

- Ecosystem Partners/getting-started-with-cohesiveft-vns3-partner-template.md
Made changes at request of customer
> CohesiveFT to Cohesive Networks name change

- Blueprints/centurylink-cloud-public-blueprint-packages.md
removed duplicate blueprint from list
> removed duplicate blueprint from list

- Managed Services/big-data-operations-guide-for-cloudera-manager-v5x-hadoop.md
- Managed Services/getting-started-with-cloudera-on-centurylink-cloud.md
Corrected broken link for the Cloudera Manager PDF.
> Updated Broken Link in Cloudera Articles

- Servers/self-service-vm-import-ovf-requirements.md
Corrected date on update (year now 2015) and added clarity to vmx requirement
> Gavin adams/kb correction

- Support/how-do-i-submit-a-feature-request.md
- Support/i-just-submitted-a-feature-request-now-what.md
- Support/uservoice-frequently-asked-questions.md
updating a few older KBs to .md
> Jruckle feature requests

- Ecosystem Partners/ecosystem-partner-list.md
Added managed technologies to ecosystem page, w/ cross-links to getting
started guides.
> Managed Services Edits

- Ecosystem Partners/getting-started-with-double-take-availability-blueprint.md
Publishing this branch so maybe we can review the kb article on live site with partner later today.  Will create another branch for other docs we're publishing today.  Thank you!
> Apr eco kbs Round 1

- Ecosystem Partners/getting-started-with-alert-logic-web-security-manager-partner-template.md
- Ecosystem Partners/getting-started-with-minecraft-server-blueprint.md
Roll that beautiful bean footage
> New ecosystem may docs

- Servers/managing-and-controlling-costs-in-centurylink-cloud.md
> HTML Flag Moved to False

- Accounts & Users/using-the-api-to-create-users.md
- Servers/log-into-the-api-with-powershell.md
New article showing users how to create a user with API (PowerShell)
> Using API to create users

- General/how-do-i-submit-an-executive-briefing-request.md
KB - How do i submit EBC Request Changes..
> DhanuKBEBCChanges

- Ecosystem Partners/getting-started-with-cohesiveft-vns3-partner-template.md
Minor tweaks to an existing doc
> Ecosystem may closeout - update to Cohesive doc

- General/centurylink-innovation-lab-faq.md
- General/centurylink-innovations-lab-faq.md
> Ctl lab faq

- AppFog/using-windows-to-deploy-your-first-application-to-appfog-step-by-step.md
Incorporate feedback from Chris Sterling
> Update Title and Prereq

- Managed Services/getting-started-with-managed-microsoft-sql-server.md
Q&A section updated to include direction on how to get MSSQL Mirroring and MSSQL Always On configured via the service task process.
> Updated Q&A section

- README.md
> added table example to readme

- README.md
added example for external sites format
> added example for external sites format

- Managed Services/managed-operating-system-frequently-asked-questions.md
Added link to https://www.centurylinkcloud.com/data-centers/ and
instructions how to identify data centers that support managed os.
> Link to Managed OS Supporting Data Centers

- Servers/patching-as-a-service.md
* Targeted server(s) must be able to access the internet
> Patching As A Service - Added a Requirement

- Servers/server-naming-convention.md
> Server Naming Convention Update

- Servers/bare-metal-faq.md
> final draft of bare metal FAQ

- Ecosystem Partners/ecosystem-partner-list.md
Re-organized categories and added a few missing partners.
> Partner List Edits

- Servers/bare-metal-faq.md
note about the partition sizes
> updated storage configuration answer

- Servers/bare-metal-faq.md
updated KB links and added a question regarding bare metal service catalog availability
> updating links for tomorrow, added service catalog question

- General/centurylink-cloud-data-center-locations.md
Noticed SG1 was missing provider and provider details…
> Added SG1 Info

- Ecosystem Partners/Marketplace Guides/getting-started-with-abantecart-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-diaspora-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-dokuwiki-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-fat-free-crm-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-gitlab-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-jenkins-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-livehelperchat-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-mean-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-opencart-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-phpbb-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-gemfire-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-greenplum-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-hd-hawq.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-prestashop-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-sharelock-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-simpleinvoices-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-squash-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-tomcat-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-wildfly-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-x2engine-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-xtremedata-dbx-blueprint.md
Hi there. Nick from @WINTR here. Just fixing up some docs that my commit analyzer found to reduce the noise of link issues on build failures before I merge in the analyzer.
> fix links in /Ecosystem Partners

- Ecosystem Partners/Marketplace Guides/getting-started-with-abantecart-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-diaspora-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-dokuwiki-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-fat-free-crm-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-gitlab-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-jenkins-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-livehelperchat-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-mean-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-opencart-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-phpbb-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-gemfire-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-greenplum-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-hd-hawq.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-prestashop-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-sharelock-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-simpleinvoices-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-squash-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-tomcat-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-wildfly-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-x2engine-blueprint.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-xtremedata-dbx-blueprint.md
Reverts CenturyLinkCloud/PublicKB#225
> Revert "fix links in /Ecosystem Partners"

- Network/latency-testing-for-centurylink-cloud-data-center-nodes.md
- Workflow/getting-started-with-clc-adapter-orchestrate.md
- Workflow/getting-started-with-clc-ansible-modules.md
Added KB articles for the following Workflow as a Service products:
- CLC-Ansible-Modules
- Wfaas-Adapter-Orchestrate
> Ansible modules

- Ecosystem Partners/Partner Integration Resources/ecosystem-program-resources-addons.md
> Update with resource links

- Managed Services/converting-unmanaged-virtual-machines-to-managed.md
Giving readers more information about what to consider prior to making
an unmanaged server managed
> Updated with requirements

- WordPress/getting-started-with-wordpress-as-a-service.md
- WordPress/wordpress-local-development.md
We're adding a KB article for a local Vagrant development environment for WordPress.
> KB Article About WordPress Local Development Environment

- Ecosystem Partners/Partner Integration Resources/ecosystem-program-resources.md
> Removing tag, correcting links

- Managed Services/managed-operating-system-frequently-asked-questions.md
Took the trailing pieces off the link to the pricing page
> Shortened link

- Managed Services/converting-unmanaged-virtual-machines-to-managed.md
We changed this design a while ago and the KB needs to be updated.
> Removed "Under Construction" Warning

- Managed Services/managed-backup-frequently-asked-questions.md
Updated per https://t3n.zendesk.com/agent/tickets/1156411
> Clarifying who Support is

- General/centuryLink-cloud-feature-availability-matrix.md
> Added GB3 Bare Metal

- General/centuryLink-cloud-feature-availability-matrix.md
> added managed backup to IL1

- Managed Services/managed-backup-frequently-asked-questions.md
Added vault location for IL1 managed backup
> Added vault location for IL1 managed backup

- WordPress/wordpress-local-development.md
Documenting the use of WordPress environment variables with a local development environment
> Documenting the use of WordPress environment variables with a local development environment

- Servers/bare-metal-faq.md
expanded on encryption details
> updating data destruction question

- Object Storage/introducing-object-storage.md
updating per https://github.com/CenturyLinkCloud/PublicPlatform/issues/513 to match service guide & converted to markdown
> update to match service guide

- Object Storage/bucket-list-operations-timing-out.md
This article will help provide some ways to mitigate an issue seen when
using the LIST command on a bucket.
> Adding KB article to address bucket LIST issue

- Servers/using-a-software-defined-virtual-nassan-on-centurylink-cloud.md
> Minor Typo in NAS-SAN KB

- Servers/cloud-server-instance-size-and-performance.md
Corrected errors in size-perf kb
> Corrected errors in size-perf kb

- Servers/cloud-server-instance-size-and-performance.md
> fixed line breaks

- Servers/using-a-software-defined-virtual-nassan-on-centurylink-cloud.md
removed RAW disk statements due to control bug on softnas
> removed RAW disk statements

- Servers/patching-as-a-service.md
I removed empty lines as they were breaking the rendering of the table
> corrected table formatting

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
updated to reflect soon to be 6 choices of vpx
> vpx-dedicated-update

- Network/load-balancing-comparison-matrix.md
added platinum edition to matrix per pending pricing update by Mary
> add-platinum-edition

- Ecosystem Partners/ecosystem-partner-list.md
Added items for vdiworks and waratek
> Updated with new partners

- Servers/using-a-software-defined-virtual-nassan-on-centurylink-cloud.md
Corrected Minor Typos in NAS/SAN KB
> Corrected Minor Typos

- Object Storage/temporary-request-redirection.md
This KB article helps explain temporary request redirection responses.
> Adding KB article for Temporary Request Redirection

- Servers/using-msdn-license-in-the-centurylink-cloud.md
Changes to MSDN licensing required rewording of the article. Also updated from HTML to md
> Update to msdn licensing

- Ecosystem Partners/Marketplace Guides/getting-started-with-vdiworks-console.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-vdiworks-host-agent.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-waratek-appsecurity.md
Correcting titles in metadata in header
> Correcting titles

- Support/ticket-prioritization-matrix.md
I needed to move Exception 2 from the Communications column to the first response column which is where it needs to be.
> Move exception 2

- Servers/server-naming-convention.md
fixed headers as it wasn't displaying properly
> fixing headers

- Service Tasks/supported-guest-operating-systems-for-ovaovf-import.md
converted to markdown and added FAQ's based on noc tickets for non-x64 platforms
> added details on hp-ux, solaris

- Network/dedicated-load-balancer-using-cli-basic-management.md
Use CLI commands to create a basic load balanced web server farm
> Dedicated Load Balancer Basic Management Using CLI

- Managed Services/big-data-operations-guide-for-cloudera-manager-v5x-hadoop.md
> fixed 404 on pdf file

- Service Tasks/supported-guest-operating-systems-for-ovaovf-import.md
added import link to OVF requirements
> added import link to OVF requirements

- Managed Services/managed-backup-frequently-asked-questions.md
added CA3 with vaulting location
> added CA3 with vaulting location

- General/centuryLink-cloud-feature-availability-matrix.md
> added CA3 to managed backup

- Network/centurylink-cloud-use-case-extending-customer-active-directory-infrastructure.md
Added links, rewrote sentences for clarity
> Updated AD extension article to include server 2012

- Managed Services/what-happens-when-RedHat-servers-are-made-managed.md
- Managed Services/what-happens-when-windows-servers-are-made-managed.md
These documents were made per
https://t3n.zendesk.com/agent/tickets/1172222. They have been reviewed
by Steve White who expressed a concern they did not have similar levels
of detail. We continue to review that, but we can amend that as time
goes by.
> Created "What Happens When Made Managed" for Windows and RHEL

- Security/centurylink-cloud-guide-to-vormetric-dsm.md
Added backup & Recovery Section to Vormetric KB
> Added backup & Recovery Section to Vormetric KB

- Network/how-to-configure-client-vpn.md
> Updated answer for using openVPN to connect to multiple accounts

- Servers/actions-that-change-server-power-state.md
new KB: Actions that change server power state
> new KB: Actions that change server power state

- Object Storage/s3cmd-object-storage-management-for-linux-machines.md
Needed to add in some additional content around the errors seen when using a newer version.
> Update Object Storage Management for Linux Machines

- Security/centurylink-cloud-guide-to-vormetric-dsm.md
> Vormetric-Typo-Fix

- Network/load-balancing-dedicated-vs-shared.md
Added a couple grammar changes, and content to the definitions.
> DedicatedVSShared-KB

- Servers/actions-that-change-server-power-state.md
updated table to make it cleaner
> updated table to make it cleaner

- Network/load-balancing-comparison-matrix.md
updated citrix support links that moved
> updated citrix support links that moved

- Support/how-do-i-report-a-support-issue.md
added phone support information as it was missing but on our public website
> added phone support information

- Service Tasks/requesting-service-tasks-on-centurylink-cloud.md
convert to markdown and update email to ctl.io
> convert to markdown and update email to ctl.io

- Managed Services/getting-started-with-cloudera-on-centurylink-cloud.md
> fix for issue #403

- Support/how-do-i-report-a-support-issue.md
updated to show details on support for managed
> updated to show details on support for managed

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-partner-template.md
> added faq on softnas

- Ecosystem Partners/Marketplace Guides/getting-started-with-pivotal-cloud-foundry.md
> fixed bad email address

- General/supported-browser-for-the-control-portal.md
Updated Firefox URL to remove the extra quote at the end.
> Supported Browsers for the Control Portal

- Blueprints/blueprints-script-and-software-package-management.md
provide basic sample xml for script package
> provide some sample xml for package.manifest

- WordPress/getting-started-with-wordpress-as-a-service.md
- WordPress/wordpress-database-access-with-external-tools.md
- WordPress/wordpress-database-access-with-phpmyadmin.md
- WordPress/wordpress-site-migration-to-centurylink-cloud.md
- WordPress/wordpress-technical-specifications.md
We're no longer providing PHPMyAdmin to let users manage their WordPress databases. They shall connect with their own external tools henceforth.
> #349: We're moving away from PHPMyAdmin

- Network/sub-account-cannot-see-parent-account-networks.md
Slight change to the wording in the failures section https://t3n.zendesk.com/agent/tickets/1194225
> Update Sub account cannot see network

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-partner-template.md
Updated to remove specific version and add HA deployment info.
> Updated SoftNAS KB article

- Service Tasks/importing-and-exporting-data-using-a-portable-storage-device.md
update import/export kb to markdown
> update import/export kb to markdown

- Ecosystem Partners/Marketplace Guides/getting-started-with-elastic-cobol.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-waratek-appsecurity.md
- Ecosystem Partners/ecosystem-partner-list.md
Initial article for Heirloom computing’s elastic cobol
> Adding article for elastic cobol

- Ecosystem Partners/Partner Integration Resources/centurylink-cloud-ecosystem-program-guide.md
Fixed heading typos and image link
> Formatting edits

- Support/backup-service-changes-faq.md
this is a supplementary KB that will go live a bit before the status.io message on 10/8. Once this is live, I will work with CSAT to have the URL to plug-in to the status message.
> Post by 10/7 - storage retirement notification

- Security/configuring-ips-notifications.md
Added all of the information needed to create and set notification destination for the client security api.
> Client Security Notification Destination API 

- Servers/self-service-vm-import-ovf-requirements.md
Needed to add an additional bullet point to explain to customers they need to know, and input, the current admin password.
> SelfService Import

- General/centuryLink-cloud-feature-availability-matrix.md
add NY1 to orchestrate locations
> add NY1 to orchestrate locations

- Object Storage/introducing-object-storage.md
Removed reference to Basho Riak
> Changed provider info

- Release Notes/2015-10-13-cloud-platform-release-notes.md
Added SDK bullet once it was approved re: Ruckle.
> Added SDK bullet to Release Notes for 10/13/2015

- Ecosystem Partners/Marketplace Guides/getting-started-with-elastic-cobol.md
Removed “guarantee”
Added Heirloom branding to KBA title
> Edited Heriloom KBA

- Network/managing-security-through-openvpn-connections.md
Added in recommendation for utilizing one cert per user, for easier management.
> Update Managing security through OpenVPN

- Network/how-to-configure-client-vpn.md
Added revised instructions on how to install the Client VPN.
> Update How to confirgure VPN

- Support/requesting-a-public-dns-ptr-record.md
Changed wording and requirements.
> Requesting DNS PTR record.

- Service Tasks/best-practices-and-preparation-for-a-virtual-machineovfova-import.md
Edits to OVF Import best practices to include the server type
> Edits to OVF Import best practices

- Managed Services/managed-operating-system-frequently-asked-questions.md
Response to https://t3n.zendesk.com/agent/tickets/1187282
**How do I Set Get Anti-Virus on a Managed RHEL Server?**
Anti-virus is not standard for RHEL. Please contact your CenturyLink
sales representative to set up a special engagement.
> Update Regarding Managed RHEL AV

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
update vpx deployment guide with choice of build edition
> update vpx deployment guide

- Support/supported-operating-systems.md
update supported OS list to include exact windows editions
> update supported OS list

- Ecosystem Partners/Marketplace Guides/getting-started-with-waratek-locker.md
adding waratek locker KB article
> adding waratek locker KB article

- WordPress/getting-started-with-wordpress-as-a-service.md
> Q and A update

- Control Portal/how-to-increase-resources-on-account.md
https://t3n.zendesk.com/agent/tickets/1195860
> edits per ticket 1195860

- Autoscale/autoscale-faq.md
updated OS support list to remove retired Ubuntu 10, and include R2 2012 DC
> updated OS support list

- Autoscale/creating-and-applying-autoscale-policies.md
updated OS list on autoscale.  found a 2nd kb with old data
> updated OS list on autoscale

- Security/configuring-ips-notifications.md
This comes with description of Email object. This comes with explanation of response json object.
> Adding Email and generic Webhook to notification json.

- Managed Services/managed-backup-frequently-asked-questions.md
update faq for retention options per managed backup team
> update faq for retention options

- Ecosystem Partners/Marketplace Guides/getting-started-with-ca-unified-infrastructure-management-on-windows.md
Initial article for CA UIM on Windows
> Initial article for CA UIM

- Accounts & Users/closing-an-account.md
add notes on cloud term commit customers
> add notes on cloud term commit customers

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-partner-template.md
fixed statement on raw disks due to bug
> fixed statement on raw disks due to bug

- General/centuryLink-cloud-feature-availability-matrix.md
> added IPS service

- Ecosystem Partners/Marketplace Guides/getting-started-with-waratek-locker.md
> Edit to add in pricing

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-partner-template.md
> fixed softnas pricing 404

- Ecosystem Partners/Marketplace Guides/getting-started-with-mesosphere-blueprint.md
> KB article for installing mesosphere via blueprint

- Security/ips-api.md
I messed up the title in the JSON object in the new doc that didn't get caught. Sorry
> I screwed up the title

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
update openvpn kb removing table due to errors rendering
> update openvpn kb

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
> openvpn-spelling-fixes

- Security/ips-api.md
I am really bad with mark down, sorry. No rush as this is purely a cosmetic change. Thanks and sorry again
> Added a space between some of the headers and # signs

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
typo in table of contents openvpn
> typo in table of contents

- Servers/bare-metal-faq.md
- Servers/server-comparison-matrix.md
@jim-phillips This should go live with the Platform release on Tuesday 11/24.
/cc @broneal for review
> 11-24 Add documentation for Bare Metal Execute Package support

- Managed Services/managed-active-directory-responsibilities.md
- Managed Services/managed-operating-system-frequently-asked-questions.md
Some clarification about who is responsible for what with Managed AD.
in FAQ
* update about new McAfee version
*clarification about cloning
> New Managed AD Responsibilities and FAQ Updates

- Ecosystem Partners/Marketplace Guides/getting-started-with-ca-ppm-on-linux.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-ca-ppm-on-windows.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-ca-unified-infrastructure-management-on-linux.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-clustrix-add-a-node.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-clustrixDB-on-centof6.md
- Ecosystem Partners/ecosystem-partner-list.md
New articles, updated partner list.
> updating partner articles

- Support/how-to-change-support-levels.md
code errors/rendering in changing support levels
> code errors/rendering in changing support levels

- Ecosystem Partners/Marketplace Guides/getting-started-with-timekeeper.md
- Ecosystem Partners/ecosystem-partner-list.md
> Adding new partner

- Release Notes/2015-11-24-cloud-platform-release-notes.md
updated to fix information on dbaas
> updated to fix information on dbaas

- Ecosystem Partners/ecosystem-partner-list.md
> correcting link text

- General/centurylink-cloud-data-center-locations.md
fixing data center locations matrix, VA1 & CA2 corrected
> fixing data center locations matrix

- Servers/patching-as-a-service.md
The script package now removes DNS 8.8.8.8 automatically after it is done.
> Deleted "Remove DNS details"

- Support/requesting-a-public-dns-ptr-record.md
Updated the requirements to include PIN requests.
> Update - Requesting a public DNS PTR record

- Servers/getting-started-how-to-securely-connect-to-your-server.md
> fixing link due to 404

- Ecosystem Partners/Partner Integration Resources/centurylink-cloud-ecosystem-program-guide.md
Aligned language to proposed edits in
https://www.ctl.io/legal/supplementalterms/
> Ecosystem Program Guide Edits

- Ecosystem Partners/ecosystem-partner-list.md
> correcting hyperlink

- Ecosystem Partners/ecosystem-partner-list.md
> fix link to cloudberry

- Ecosystem Partners/Marketplace Guides/getting-started-with-a10-vthunder-partner-template.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-avni-software-defined-cloud-partner-template.md
- Servers/patching-as-a-service.md
removed references to centurylink.com and fixed to ctl.io
> removed references to centurylink.com

- Managed Services/managed-active-directory-responsibilities.md
> Edit spelling

- Ecosystem Partners/Marketplace Guides/getting-started-with-Netwrix-Auditor.md
- Ecosystem Partners/ecosystem-partner-list.md
> Adding new partners

- Ecosystem Partners/Marketplace Guides/getting-started-with-vdiworks-console.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-vdiworks-host-agent.md
> Updating contact info

- Support/pin-authentication-for-support-requests.md
Added in a note asking for the username when multiple accounts are used.
> Update Pin Request

- Object Storage/object-storage-service-points.md
- Object Storage/using-object-storage-for-backup-as-a-service.md
- Object Storage/using-object-storage-with-a-cloud-storage-gateway.md
I fixed some formatting issues with the new service point KB.  I think linked two other articles to the service point KB.
> Fixed formatting issues and updated 2 KB articles

- Security/centurylink-cloud-guide-to-vormetric-dsm.md
include simple backup services in Vormetric kb:  backup and restore considerations
> include simple backup services in Vormetric kb

- Ecosystem Partners/Marketplace Guides/getting-started-with-appsfreedom-centOS.md
- Ecosystem Partners/ecosystem-partner-list.md
> New Blueprint article

- Network/dedicated-load-balancer-required-configuration-change.md
> Load balancer update kb

- General/centuryLink-cloud-feature-availability-matrix.md
> add RDBS to matrix

- Ecosystem Partners/ecosystem-partner-list.md
Fixed CR that was breaking up the Dev Framework table.
> Fixed typo

- Ecosystem Partners/ecosystem-partner-list.md
> correcting layout

- Ecosystem Partners/Marketplace Guides/getting-started-with-orientdb.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-vdiworks-console.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-yellowfin.md
> corrections

- General/centuryLink-cloud-feature-availability-matrix.md
> update RDBS language

- Network/how-to-add-public-ip-to-virtual-machine.md
> added hairpin details

- Ecosystem Partners/Marketplace Guides/getting-started-with-cloudberry-lab-backup-enterprise-blueprint.md
> fixing cloudberry images

- Servers/understanding-vm-deployment-options-and-power-states.md
added details about managed apps billing
> added details about managed apps billing

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
update sql BP kb around version mobility
> update sql BP kb

- Ecosystem Partners/Marketplace Guides/getting-started-with-odrive-file-server-blueprint.md
> correcting URL

- Accounts & Users/using-the-api-to-create-users.md
Updated step 2 with correct command. Further information can be found here: https://t3n.zendesk.com/agent/tickets/1234645
> Update API to create users

- Managed Services/managed-active-directory-responsibilities.md
- Managed Services/managed-operating-system-frequently-asked-questions.md
- Managed Services/monitors-for-managed-operating-systems.md
Updated
1. In Managed AD Responsibilities: added Bulk Create Users and Groups
2. In Managed OS FAX: Updated Sales and Support phone numbers; “cannot
restore a managed server as an unmanaged;” Type fix
Added monitors-for-managed-operating-systems.md
> 2 Updates and 1 Add to Managed OS KBs

- Ecosystem Partners/Marketplace Guides/getting-started-with-couchbase-blueprint.md
- Ecosystem Partners/ecosystem-partner-list.md
> adding couch base article

- Support/how-do-i-report-a-support-issue.md
Distinguished between support and request email
> Updated Support Info for Managed Services

- Servers/centurylink-cloud-guide-to-cli.md
This is a walk-through of both Python SDK based CLI and GO based CLI.
> Create CenturyLink Cloud Guide to CLI

- Security/configuring-ips-notifications.md
- Security/getting-started-with-ips.md
- Security/ips-api.md
- Security/ipsAnywhere.md
Updates for Client Security KB's.
> Trello Card #926 - Client Security KB Fixes/Updates.

- Security/IPS-on-DCC.md
> IPS on DCC KB

- Servers/using-powershell-and-v1-api-to-get-all-servers.md
Title: Using the V1 API to get all Servers in an Account Alias with PowerShell
> New KB - Using PowerShell to Get Server Details

- Blueprints/building-windows-2012-script-packages.md
updated windows 2012 scripts (fix 404, code to markdown)
> updated windows 2012 scripts

- General/free-trial-faq.md
Per discussion with Rich Dubose.
> Removed time constraint info

- Security/getting-started-with-ips.md
> Card #949 - Ticket 1237139 - KB Updates.

- Network/hairpin-nats.md
> updated hairpin NAT KB

- Container Services/getting-started-with-kubernetes.md
Match v0.3 of our kubernetes release
> Update Kubernetes KB with latest info

- Network/how-to-add-public-ip-to-virtual-machine.md
> updated hairpin note

- Servers/cloud-server-instance-size-and-performance.md
update cloud sizing to include vNIC max
> update cloud sizing to include vNIC max

- General/centuryLink-cloud-feature-availability-matrix.md
Edited the Availability KB to correct Relational DB name from
Relational Database to Relational DB.
> Relational DB-Availability KB Edit

- Managed Services/managed-operating-system-frequently-asked-questions.md
Recommended simple backup for Managed OS.
> Managed OS FAQ

- Managed Services/managed-operating-system-frequently-asked-questions.md
to more accurately describe the backup product as separate from Managed
OS.
> Updated verbiage

- Ecosystem Partners/Partner Integration Resources/centurylink-cloud-ecosystem-program-guide.md
> Removed EPA Reference

- Ecosystem Partners/Marketplace Guides/getting-started-with-cloudfuze-blueprint.md
Requested update from ticket - https://t3n.zendesk.com/agent/tickets/1245379
> Update CloudFuze getting started page

- Support/how-do-i-report-a-support-issue.md
fix table that isn't rendering
> fix table that isn't rendering

- Servers/using-owncloud-with-rdbs.md
> fix date typo on owncloud kb

- Support/how-do-i-report-a-support-issue.md
> fix control url

- Network/add-or-remove-network-interface-to-server-using-go-cli.md
> update go cli add vnic

- Network/add-or-remove-network-interface-to-server-using-go-cli.md
remove text about case sensitive
> remove text about case sensitive

- Ecosystem Partners/Partner Integration Resources/centurylink-cloud-ecosystem-program-guide.md
> Added OnBoarding QuickStart Program

- Disaster Recovery/safehaven-gracefully-shutdown-srn.md
> Update SafeHaven Gracefull Reboot doc

- Security/IPS-on-DCC.md
Updated Formatting of IPS for DCC FAQ and fixed a few links.
> Updated Formatting of IPS for DCC FAQ

- Servers/centurylink-cloud-guide-to-cli.md
Updates to Create CenturyLink Cloud Guide to CLI with OS Patching
> Updates to Create CenturyLink Cloud Guide to CLI with OS Patching

- Security/ips-api.md
> Adding Syslog FW Rules

- Servers/centurylink-cloud-guide-to-cli.md
Updates to Create CenturyLink Cloud Guide to CLI with Simple Backup Service
> Updates to Create CenturyLink Cloud Guide to CLI with Simple Backup Service

- Backup/simple-backup-service-faqs.md
Updated FAQs & Added TOC for SBS
> Updated FAQs & Added TOC

- Disaster Recovery/build-safehaven-base-image-template-from-ubuntu.md
update links with 3.1.1u1/GA links
> update build safehaven template KB

- Disaster Recovery/SAHA31-Checkpoints.md
added linux checkpoints showing as unknown info
> update SafeHaven-Checkpoints with linux info

- Servers/centurylink-cloud-guide-to-cli.md
Adding the modify example in SBS section
> Adding the modify example in SBS section

- General/centuryLink-cloud-feature-availability-matrix.md
- General/centurylink-cloud-data-center-locations.md
@srveit or @jim-phillips Don’t merge until the 12th.
> AU Release KB

- General/centurylink-cloud-data-center-locations.md
> fixed url to sydney

- Ecosystem Partners/Marketplace Guides/getting-started-with-netwrix-auditor-80.md
because the KB generator is messing up the images call
> changing logo

- Disaster Recovery/safehaven-configure-email-alerts.md
added unsupported pw special characters causing errors
> update email with unsupported pw chars

- Object Storage/using-object-storage-via-rest-api-aws-sdk.md
> fix typo in OS API doc

- Network/changing-ip-address-on-a-centurylink-cloud-hosted-machines.md
Update per https://t3n.zendesk.com/agent/tickets/1257615
> re-write per ticket 1257615

- Support/using-the-help-desk-web-ui.md
https://t3n.zendesk.com/agent/tickets/1255339
> Update per PM 1255339

- Security/ips-api.md
> Fixing Typo

- Security/ipsAnywhere.md
Modified endpoint URL for Windows install and Windows uninstall
> Modified endpoint URL for Windows install and Windows uninstall

- Ecosystem Partners/Marketplace Guides/getting-started-with-hashicorp-terraform.md
nix plugin refs, link add'l resources
> Eco / Terraform

- Support/how-do-i-report-a-support-issue.md
> added chat requirements

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
updated to build 2.0.26 openvpn
> updated to build 2.0.26 openvpn

- Network/centurylink-cloud-ids-idp-platform-faq.md
> update ips faq

- Object Storage/object-storage-error-code-503-slow-down.md
This is the initial commit for the error code 503 kb article.
> Initial commit for error code 503 kb

- Database/mysql-rdbs-faqs.md
- Database/replication-and-failover.md
Updated link to API documentation and clarification around asynchronous
replication.
> RDBS KB Updates

- Network/centurylink-cloud-use-case-extending-customer-active-directory-infrastructure.md
typo correction and added ntdsutil fsmo query note, moved a few things around
> typo correction

- Disaster Recovery/SAHA31-ClusterConfiguration.md
updated version to 3.1.1/dropbox urls
> updated version to 3.1.1/dropbox urls

- General/free-trial-faq.md
Update KB per Zendesk ticket request to clarify that there is not an expiration date placed on new Trial accounts.  Removed the AppFog verbiage and link.
> Updates to KB

- Security/getting-started-with-ips.md
> FW Rule Formating Change

- General/centuryLink-cloud-feature-availability-matrix.md
> typo fix in matrix

- Ecosystem Partners/Marketplace Guides/getting-started-with-appcito-cafe.md
http://www.appcito.com/products/service-packages/
> Fixed broken link

- Support/ut1-environment-migration.md
remove premium for UT1 migration kb
> remove premium for UT1 migration kb

- Disaster Recovery/build-safehaven-base-image-template-from-ubuntu.md
> update baseimage url

- Support/zendesk-login-help-for-helpdesk-ticketing-and-kb-access.md
Correction request from ticket [#1284020](https://t3n.zendesk.com/agent/tickets/1284020). Converted content to Markdown. Updated/added hyperlinks. Minor grammar/formatting corrections.
> Correction for zendesk-login-help-for-helpdesk-ticketing-and-kb-access.md

- Backup/simple-backup-service-faqs.md
fix backup faq formatting on logs
> fix backup faq formatting on logs

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-appliance.md
updating to reflect the OS switch that happens when the appliance is built.
> OS comment

- General/centuryLink-cloud-feature-availability-matrix.md
include 4 new locations for rdbs
> include 4 new locations for rdbs

- Database/connecting-to-mysql-rdbs-over-ssl.md
Customers submit tickets for inability to connect to their database
via ssl. Added error description and fix.
> Add cause and remediation for customer ssl db connection problems

- General/centuryLink-cloud-feature-availability-matrix.md
Reverts CenturyLinkCloud/PublicKB#1059
> Revert "include 4 new locations for rdbs"

- General/centuryLink-cloud-feature-availability-matrix.md
Reverts CenturyLinkCloud/PublicKB#1063
> Revert "Revert "include 4 new locations for rdbs""

- Object Storage/object-storage-regions-and-service-points.md
NY1 is currently the primary data center for us-east.  I am updating the document to reflect that.
> Updated US-East

- Network/centurylink-cloud-public-ip-listing.md
fix public ip kb formatting and support information that was not correct
> fix public ip kb formatting

- Service Tasks/importing-and-exporting-data-using-a-portable-storage-device.md
Added 7-Zip as an example for the recommended tools for encryption
> Added 7-Zip to Portable Storage KB

- Support/ticket-prioritization-matrix.md
Update time for service task team to be 7am-7pm 
https://trello.com/c/MDRvvbHY
> Update ticket prioritization matrix - change hours for Service Task Team

- Service Tasks/requesting-service-tasks-on-centurylink-cloud.md
Update hours for service task team to be M-F 7am - 7pm pacific time
> Update requesting-service-tasks-on-centurylink-cloud.md - change hours for Service Task Team

- Disaster Recovery/checkpoints-rabbitmq.md
An overview of the importance of rabbitmq w/r/t SafeHaven and how to manually establish queues for protection groups that are missing them.
> Create file Checkpoints-rabbitmq.md

- Ecosystem Partners/Marketplace Guides/getting-started-with-yellowfin.md
> updating version

- Service Tasks/best-practices-and-preparation-for-a-virtual-machineovfova-import.md
> added note about vmx 8

- Support/pin-authentication-for-support-requests.md
Changed wording for new Control update.
> pin-authentication-for-support-requests.md

- Control Portal/how-to-increase-resources-on-account.md
> Add public-ip to resource limit increase KB

- Managed Services/getting-started-with-managed-apache.md
- Managed Services/getting-started-with-managed-microsoft-iis.md
- Managed Services/getting-started-with-managed-mysql.md
Added availability of MySQL 5.7 version 
Added availability of IIS 8.5 version
Added availability of Apache Httpd 2.4 with PHP 5.6
> Updated MySQL, IIS and Apache Httpd   with available Version

- General/centurylink-cloud-data-center-locations.md
> added VA2 to locations matrix

- Backup/simple-backup-service-faqs.md
Added Q/A for stopping an in-progress restore by restarting Simple Backup Service on the server.
> Add restore job cancellation to Restores section

- Object Storage/object-storage-regions-and-service-points.md
Updating the primary and secondary datacenters
> Updating the primary and secondary datacenters

- Servers/patching-as-a-service.md
script & blueprint names incorrect in patching
> script & blueprint names incorrect in patching

- Control Portal/how-to-increase-resources-on-account.md
I corrected a few typos, fixed an incorrect instruction and added clarity regarding data center resource inheritance.
> Updated How To: Increase resources on account

- General/centuryLink-cloud-feature-availability-matrix.md
> add lbaas for launch

- Release Notes/2016/2016-08-30-cloud-platform-release-notes.md
> fix runner details for sql

- Backup/linux-rdp.md
I have added the sections for RHEL6x, CENTOS6x, and CENTOS7x to provide support for additional operating systems.
> Update the KB for linux-rdp.md

- Release Notes/2016/2016-08-30-cloud-platform-release-notes.md
> images broken and now fixed

- Release Notes/2016/2016-08-30-cloud-platform-release-notes.md
fixed legacy NLB pricing which was wrong
> fixed legacy NLB pricing which was wrong

- Release Notes/2016/2016-08-30-cloud-platform-release-notes.md
> SBS Update

- Release Notes/2016/2016-08-30-cloud-platform-release-notes.md
> minor fix in release notes

- Autoscale/creating-and-applying-autoscale-policies.md
fix tables in autoscale kb that were not rendering
> fix tables in autoscale kb

- Network/load-balancing-comparison-matrix.md
> fix urls for citrix

- Support/smtp-relay-deactivation-faq.md
> Create the EOL message for SMTP Relay.

- Servers/centurylink-cloud-guide-to-cli.md
Update CLI Guide with execute a package
> Update CLI Guide with execute a package

- Servers/understanding-vm-deployment-options-and-power-states.md
Adding links to pricing catalog
> Pricing Catalog Link

- Servers/centurylink-cloud-guide-to-cli.md
Update CLI guide with public IP management
> Update CLI guide with public IP management

- Support/how-do-i-report-a-support-issue.md
made content accurate regarding reopening a ticket, some additional language about providing user PIN, and changed "support staff" to "Customer Care team"
> Updated to make current

- Support/how-to-change-support-levels.md
more precise language, removed legacy UX images, now links to PIN auth KB
> updates for precision, accuracy

- Support/summary-of-cloud-based-post-Sales-support.md
better language regarding Customer Care (support), DSE, and Customer Excellence
> updates to bring current

- Support/submitting-custom-requests.md
small changes for accuracy and bring forward the article date
> reviewed and updated

- Support/how-do-i-submit-a-feature-request.md
Additional link to UserVoice FAQ, replaced "feature request" with "Feature Request" as it is an operationalized process and identified self as author (replaced Richard Seroter)
> Additional link to UserVoice FAQ

- Support/smtp-relay-deactivation-faq.md
> Updating SMTP Relay EOL Message

- Support/ticket-prioritization-matrix.md
content is fine, updated the date to reflect that the information is current and accurate
> reviewed and updated the date

- Servers/bare-metal-faq.md
> Bare Metal FAQ

- Servers/bare-metal-faq.md
> Bare Metal Correct Server Configurations

- Servers/actions-that-change-server-power-state.md
updated power state for Ubuntu 16
> updated power state for Ubuntu 16

- Servers/centurylink-cloud-guide-to-cli.md
Update CLI guide with keywords for better understanding of the commands
> Update CLI guide with keywords

- Servers/configuring-raid-on-bare-metal-servers.md
fix numbering on bare metal raid kb
> fix numbering on bare metal raid kb

- Service Tasks/importing-and-exporting-data-using-a-portable-storage-device.md
> Update to remove 1TB limit on external HDD for Service Task Data Import/Export

- Servers/configuring-raid-on-bare-metal-servers.md
added note about wizard on bare metal raid
> added note about wizard on bare metal raid

- Servers/bare-metal-faq.md
fix table for better viewing Bare Metal
> fix table for better viewing Bare Metal

- Network/load-balancing-comparison-matrix.md
> fix LB Matrix link

- Servers/understanding-vm-deployment-options-and-power-states.md
update power state kb on bare metal
> update power state kb on bare metal

- Autoscale/creating-and-applying-autoscale-policies.md
> Fix autoscale table

- Servers/bare-metal-faq.md
> fixed bare metal faq OS list

- Service Tasks/supported-guest-operating-systems-for-ovaovf-import.md
add ubuntu 16 to guest support
> add ubuntu 16 to guest support

- Servers/bare-metal-faq.md
> added api sku's for BM

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
> update for 2.1.4 openvpn

- Support/what-can-you-expect-from-centurylink-cloud-on-an-incident.md
update support incident legacy kb
> update support incident legacy kb

- Servers/creating-and-managing-server-snapshots.md
- Servers/how-to-clone-a-virtual-machine-os-instance.md
update kbs around cloning VM's with snapshots
> update kbs around cloning VM's with snapshots

- Servers/how-to-clone-a-virtual-machine-os-instance.md
add managed OS exclusion to cloning
> add managed OS exclusion to cloning

- Release Notes/2016/2016-11-08-cloud-platform-release-notes.md
Enhancements had an incorrect number of items, this has been fixed.
> Fixed number of items in Enhancements

- Object Storage/using-object-storage-via-rest-api-aws-sdk.md
added a carriage return to fix code block formatting issue and removed
an unnecessary pre block
> fix for formatting issues

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
> remove extra character

- index.md
> Adding Marketplace to KB Index

- Object Storage/using-object-storage-from-3rd-party-tools.md
card: https://trello.com/c/TGMTSmRI/1605-fix-steps-in-kb-using-object-storage-
from-3rd-party-tools-for-aws2-authentication
> fixing cyberduck process

- Ecosystem Partners/Marketplace Guides/getting-started-with-vormetric-dsm.md
> Updating to reference runner

- Object Storage/using-object-storage-for-backup-as-a-service.md
> Fix backup as a service

- General/getting-started-with-the-service-catalog.md
> update - how to find menu selection

- Mail/smtp-relay-services-simple.md
> Change to first line re: EOS & EOL

- Support/smtp-relay-deactivation-faq.md
> Revision to EOS/EOL reference

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
- Managed Services/getting-started-with-managed-microsoft-sql-server.md
Mssql updates for license change
> Mssql updates for license change

- Ecosystem Partners/Marketplace Guides/getting-started-with-vormetric-encryption-agent-deployment-blueprints.md
> updating pricing language

- Network/dedicated-load-balancer-license-management.md
KB not rendering properly due to front matter - fixed
> fixed front matter formatting/edits

- Servers/platform-socket-to-vcpu-allocation.md
> fix table in vcpu to socket

- Servers/hyperscale-server-faq.md
Automatic Standard/Premium backups have been retired
> Remove reference to automatic backups

- Managed Services/managed-operating-system-frequently-asked-questions.md
UK requested we change the sales phone number in all places from
+44 (0) 207 400 5600
to
+44 (0) 118 309 4886
@srveit please merge
> New UK Sales Phone Number

- Managed Services/managed-backup-frequently-asked-questions.md
> New UK phone number

- Disaster Recovery/SAHA4.0 Networking.md
cleaned up inconsistent use of punctuation
> Update SAHA4.0 Networking.md

- Service Tasks/importing-and-exporting-data-using-a-portable-storage-device.md
Updated prequisites, combined import/export sections, added additional FAQs
https://trello.com/c/kXsJkh2o
> Updates to Service Task Public Import/Export KB

- Network/latency-testing-for-centurylink-cloud-data-center-nodes.md
add custom endpoints for latency testing kb
> add custom endpoints for latency testing kb

- General/free-trial-faq.md
update trial kb to remove references to solution architect follow up
> update trial kb

- General/updating-credit-card-information.md
update kb on credit card to remove legacy UI path
> update kb on credit card

- General/centuryLink-cloud-feature-availability-matrix.md
> updated LBaaS Locations

- Support/rhel-epel-ca-certificates.md
Add KB article for RHEL certificate 'fix'
https://trello.com/c/Kikzoajt/375-2-add-kb-article-for-rhel-certificate-fix
> Rhel epel ca certificates

- Accounts & Users/closing-an-account.md
The following language was added to the "Overview" section:
"Please be aware that it is not possible to recover an account or the associated assets after the account is deleted.  Proceed cautiously to ensure you've recovered all data before proceeding to deletion."
> Deleted Account Cannot be Recovered

- Servers/centurylink-cloud-guide-to-cli.md
Update CLI guide with PowerState and DisplayName
> Update CLI guide with add disks and query PowerState and DisplayName

- Backup/simple-backup-service-how-it-works.md
add Sydney to simple backup matrix
> add Sydney to simple backup matrix

- Managed Services/getting-started-with-managed-microsoft-sql-server.md
@srveit or @jim-phillips Please merge.
> Adding SQL 2016

- Release Notes/2017/2017-01-31-cloud-platform-release-notes.md
Created release notes for 1312017 release
> New release notes for 20170131 release

- Release Notes/2017/2017-01-31-cloud-platform-release-notes.md
> Update to callout Runner in the heading

- Managed Services/getting-started-with-managed-active-directory.md
removing bad markdown in html kb
> removing bad markdown in html kb

- LBaaS/LBaaSFAQ.md
> updates to LBaaS FAQ

- Support/smtp-relay-deactivation-faq.md
Readded SMTP EOL FAQ with updates
> Readded SMTP EOL FAQ with updates

- Support/how-do-i-report-a-support-issue.md
> fix chat requirements

- Network/load-balancing-comparison-matrix.md
> add lbaas new locations

- Support/smtp-relay-deactivation-faq.md
Correcting a typo in in smtp-relay-deactivation-faq.md
> Correct typo in smtp-relay-deactivation-faq.md

- ElasticBox/partner-cloud-integration-azure-usage-estimates.md
Changed the title of the KB so it is more descriptive and unique.
> Change Title

- Partners/partners-requesting-customer-trial.md
@srveit or @jim-phillips Please merge
> Removing the $2500 credit option

- Network/how-to-add-public-ip-to-virtual-machine.md
add note about secondary interface
> add note about secondary interface

- Accounts & Users/role-permissions-matrix.md
> fixed link

- Compliance/Centurylink-FERPA.md
@srveit @jim-phillips Please merge
https://ctliotest.atlassian.net/browse/CTLIO-406
> Remove reference to SOC 3

- Cloud Application Manager/getting-started-enterprise-setup-onboarding.md
> Fix default admin account adding the missing '@'

- Release Notes/2017/2017-02-28-cloud-platform-release-notes.md
> Release Notes for 2-28-17

- Orchestrate/key-value.md
@srveit @jim-phillips 
also for
https://ctliotest.atlassian.net/browse/CTLIO-418
> Fix broken link

- Control Portal/getting-started-with-white-labeling.md
@srveit or @jim-phillips 
Another for
https://ctliotest.atlassian.net/browse/CTLIO-418
> Fixing broken link

- Cloud Application Manager/API/api-boxes.md
- Cloud Application Manager/API/api-future.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-deleteCustomerAccount.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-users.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
> Fix minor style details and update support account

- Servers/centurylink-cloud-guide-to-doubletake-dr.md
@srveit @jim-phillips please merge
part of
https://ctliotest.atlassian.net/browse/CTLIO-418
> fixing link

- Backup/automating-sbs-on-api-v2.md
@srveit or @jim-phillips 
another for:
https://ctliotest.atlassian.net/browse/CTLIO-418
> Fixing Broken Links

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-new.md
Fixed Provider KB link
Clarified reason for currently requiring CLC account
> Fixed link, clarified intent.

- Network/load-balancing-comparison-matrix.md
> adding source IP to lbaas

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
added additional ELB actions for IAM policy
> added additional ELB actions for IAM policy

- General/centurylink-cloud-data-center-locations.md
> updated CA1 to CTL location

- Network/centurylink-cloud-guide-to-openvpn-access-server.md
> update openvpn code and url

- Control Portal/how-to-configure-mx-records.md
Old: Navigate to Domains -> DNS. Select the DNS zone that corresponds with your email domain
New: Navigate to Network and select DNS. Select the DNS zone that corresponds with your email domain
RE ticket: https://t3n.zendesk.com/agent/tickets/1374530
> Update navigation based on UI updates

- Ecosystem Partners/General/ecosystem-partner-list.md
adding fortinet to partner list
> adding fortinet to partner list

- Support/supported-operating-systems.md
https://t3n.zendesk.com/agent/tickets/1363190
> Explicit statement: no in-place OS upgrade support

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
fixed location of tenant ID in azure
> fixed location of tenant ID in azure

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-permissions.md
updated azure feature list with breaks
> updated azure feature list with breaks

- Dedicated Cloud Compute/Release Notes/2017-04-05-new-dcc-ui-release-notes.md
Adding the BETA 5 release notes to the new KB area for DCC.
> BETA 5 Release Notes

- Network/load-balancing-comparison-matrix.md
> added WAF to comparison

- Object Storage/object-storage-3rd-party-compatibility.md
> new kb on compatible storage

- General/centuryLink-cloud-feature-availability-matrix.md
updated feature matrix for network exchange
> updated feature matrix for network exchange

- Network/network-exchange-connectivity-matrix-configuration-guide.md
fixed table rendering in netx matrix
> fixed table rendering in netx matrix

- Network/network-exchange-clc-colocation-endpoint-guide.md
removed holder text for SLA as no data supplied
> removed holder text for SLA as no data supplied

- Network/network-exchange-faqs.md
fixed spacing in network exchange faq
> fixed spacing in network exchange faq

- Backup/simple-backup-service-faqs.md
Added the following to the Retention section:
Q: What is the maximum retention period for backups?
A: 18263 days (approximately 50 years)
> Adding max retention period detail

- General/centurylink-cloud-data-center-locations.md
> Updated locations to Cyxtera

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
> added faq for costing VPX

- Ecosystem Partners/General/ecosystem-partner-list.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-alert-logic-threat-manager-partner-template.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-alert-logic-web-security-manager-partner-template.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-instant-api.md
- Release Notes/2015/2015-05-06-cloud-platform-release-notes.md
- Security/getting-started-with-flexsecure.md
Reverts CenturyLinkCloud/PublicKB#1692
> Revert "Remove old eco kbs"

- Ecosystem Partners/Marketplace Guides/getting-started-with-softnas-cloud-file-gateway-appliance.md
Added note about allocating more storage at deployment, steps for requesting support reassign the /boot disk, removed email notification section
> Update SoftNAS KB

- Network/centurylink-cloud-public-ip-listing.md
PRed and approved in https://t3n.zendesk.com/agent/tickets/1374448
> Add FAQ and answer

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
> fixed dedicated vpx spacing

- Release Notes/2017/2017-05-09-cloud-platform-release-notes.md
> Release Notes 5-09-2017

- Cloud Application Manager/Getting Started/getting-started-create-user.md
> Create Cloud Application Manager Users

- Servers/how-to-create-customer-specific-os-templates.md
update customer template kb link
> update customer template kb link

- Support/CenturyLink Cloud Infrastructure Disclosure Confidentiality.md
Article was created for PM item https://t3n.zendesk.com/agent/tickets/1393568 to provide a public statement to customers who request proprietary and confidential information about our platform infrastructure.
> Create CenturyLink Cloud Infrastructure Disclosure Confidentiality KB

- Network/load-balancing-comparison-matrix.md
> added URI to NLB matrix

- Network/load-balancing-comparison-matrix.md
> updated NLB matrix

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
Issue where copy and past is not working correctly because characters are not correct.
> Update to characters in KB

- Release Notes/2017/2017-06-08-cloud-platform-release-notes.md
> Release Notes 170608

- Private Node/centurylink-private-node.md
> private node typo

- General/centuryLink-cloud-feature-availability-matrix.md
> Removing VA2 from netx matrix

- Cloud Application Manager/Core Concepts/providers.md
removed developer edition from CAM providers list
> removed developer edition from CAM providers list

- Network/troubleshooting-potential-network-performance-issues-with-mtr.md
troubleshooting-potential-network-performance-issues-with-mtr.md
> Adding KB (troubleshooting-potential-network-performance-issues-with-mtr.md)

- Network/troubleshooting-potential-network-performance-issues-with-mtr.md
The majority of this document is Wiki markup, so that needs to change.
> Fix meta for ContentisHTML to false

- General/centurylink-cloud-data-center-locations.md
> Added DE3 to locations

- Managed Services/managed-backup-frequently-asked-questions.md
> per dpb pricing approval june 2017

- Managed Services/managed-backup-frequently-asked-questions.md
revised spacing in rows 42 - 47 and revised price  in row 46
> revised spacing in rows 42 - 47 and revised price  in row 46

- Cloud Application Manager/Core Concepts/providers.md
> added DCC to providers in CAM

- Backup/simple-backup-service-faqs.md
> Fixed headline capitalization

- Managed Services/managed-backup-frequently-asked-questions.md
> Fix text referencing the prices

- Managed Services/getting-started-with-managed-mysql.md
updated managed mysql licensing faq
> updated managed mysql licensing faq

- Dedicated Cloud Compute/DCC Foundation/dcc-foundation-faq.md
Updated FAQ to be more readable.
> Made it more readable

- General/centuryLink-cloud-feature-availability-matrix.md
> added new netx locations

- Network/load-balancing-comparison-matrix.md
> added DE3 to Matrix

- Servers/bare-metal-faq.md
> updated bare metal faq

- General/centuryLink-cloud-feature-availability-matrix.md
added 2 new bare metal locations for release this week
> added 2 new bare metal locations

- Object Storage/object-storage-regions-and-service-points.md
> add germany endpoint

- Cloud Application Manager/Deploying Anywhere/using-centurylink-cloud.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
> Shutdown and Terminate instances summary

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
> Add more permissions on AWS and shutdown and terminate instances summary

- Release Notes/2017/2017-07-18-cloud-platform-release-notes.md
Update 7-18 release notes to include german object storage & Windows 2016 release
> Update 7-18 release notes

- Backup/simple-backup-service-how-it-works.md
adding germany endpoint for sbs
> adding germany endpoint for sbs

- Servers/self-service-vm-import-ovf-requirements.md
Added note about disabling DHCP in the general ovf import guidelines.
> self-service-vm-import-ovf-requirements.md

- Object Storage/object-storage-3rd-party-compatibility.md
> adding EMC Cloudarray

- Support/The Urgent Incident Process
> adding KB (The Urgent Incident Process)

- Managed Services/managed-operating-system-frequently-asked-questions.md
@srveit or @jim-phillips please review and merge.
https://ctliotest.atlassian.net/browse/CTLIO-703
> Correcting an unfinished sentence.

- Backup/simple-backup-service-how-it-works.md
> added UK endpoint to sbs

- Servers/bare-metal-faq.md
Updated SKU's to reflect 4TB disks in DE3 & GB1
> Updated SKU's to reflect 4TB disks in DE3 & GB1

- Servers/bare-metal-faq.md
Updated Bare Metal SKUs and configurationID's for API
> Updated Bare Metal SKU

- Marketplace/Marketplace Updates/Marketplace Updates July 2017.md
Incorrect URL resulted in a 404.
> Update Marketplace Updates July 2017.md

- Cloud Application Manager/API/api-providers.md
- Cloud Application Manager/API/instances-api.md
@lyzalou This updates API documentation with unregistered instances endpoints and operations:
list unregistered instances, single and bulk import, cancel, retry.
https://elasticbox.atlassian.net/browse/EBE-5278
> [EBE-5278] Update documentation with API for unregistered instances

- Security/centurylink-cloud-guide-to-vormetric-dsm.md
removed legacy std backup options
> removed legacy std backup options

- General/centuryLink-cloud-feature-availability-matrix.md
> removed IL1 & UC1 hyperscale

- Managed Services/converting-unmanaged-virtual-machines-to-managed.md
repaired tables broken in last PR from customer care
> repaired tables broken in last PR

- Release Notes/2017/2017-08-29-cloud-platform-release-notes.md
Added August 29 2017 Release notes
> Added August 29 2017 Release notes

- Release Notes/2017/2017-09-12-cloud-platform-release-notes.md
Product release Notes for 9.12.17
> Release Notes Update 9.12.17

- Servers/creating-and-managing-server-snapshots.md
adding note about simple backup manifest
> adding note about simple backup manifest

- Servers/timekeeping-best-practices-for-windows-servers.md
timekeeping-best-practices-for-windows-servers.md
> Adding KB (timekeeping-best-practices-for-windows-servers.md)

- Backup/simple-backup-service-how-it-works.md
updated encryption notes for CTL location endpoints
> updated encryption notes

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-support.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-support.md
@srveit or @jim-phillips please merge for tomorrow’s deployment 9/14
https://ctliotest.atlassian.net/browse/CTLIO-813
> Fix 2 last links 

- Servers/self-service-vm-import-ovf-requirements.md
Added requirement for "Manifest must use the SHA1 hashing algorithm"
> Update to self-service-vm-import-ovf-requirements.md

- Managed Services/created-a-managed-server-now-what.md
added technical requirements for managed OS
> added new details for managed os

- Cloud Application Manager/Managed Services/Deploying_Managed_MS_SQL_to_AWS.md
updated KB with additional detail
> Update Managed MS SQL KB

- Runner/product-config.md
Added additional documentation regarding valid config.yml components
> Runner product

- Blueprints/evaluate-microsoft-sql-server-using-blueprints.md
Added 2016 Windows support to eval edition
> Added 2016 Windows support to eval edition

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
> added new build to vpx list

- Release Notes/2017/2017-10-24-cloud-platform-release-notes.md
> Release Notes 10/24/2017

- Servers/how-to-change-a-server-administrator-password.md
https://t3n.zendesk.com/agent/tickets/1445406
> Minor updates see ticket

- Runner/product-config.md
> fixing code highlight errors

- Network/load-balancing-comparison-matrix.md
> added criteria GeoIP filter

- Runner/product-config.md
fixing more code errors in runner kb
> fixing more code errors in runner kb

- Service Tasks/importing-and-exporting-data-using-a-portable-storage-device.md
> fixing import kb numbering

- Marketplace/Providers/software-as-a-service-saas-api.md
> Add termination endpoint documentation

- Cloud Application Manager/Administering Your Organization/resource-tags.md
> updated tags location in CAM

- General/centurylink-cloud-data-center-locations.md
@srveit if possible, would love to get this updated with tomorrow's deployment 11/7/17
https://ctliotest.atlassian.net/browse/CTLIO-931
> New location for GB1

- Network/dedicated-load-balancer-license-management.md
PM# 1456214
Update License Installation process to include steps to save running config before rebooting.
> Update VPX License Management to Save Config

- Servers/bare-metal-faq.md
updated bare metal faq for GB1
> updated bare metal faq for GB1

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
adding sql notes for price changes
> adding sql notes for price changes

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
Add an extra step for clarification.
@DiegoSanjuan and @gsanchezu please review
> [EBE-5550] Update Microsoft Azure instructions for App Registration

- Cloud Application Manager/Cloud Optimization/CloudApplicationManagerAnalyticsAWSSetup.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-existing.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-new.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-connect-aws.md
removing the words share shift
> Removing Share-Shift Terms

- Control Portal/how-to-increase-resources-on-account.md
Emphasized being paying customer. Added link for validating identity.
> Update how to increase resources on account.

- Cloud Application Manager/Administering Your Organization/admin-overview.md
- Cloud Application Manager/Administering Your Organization/resource-tags.md
> [CAM-4361] Change Admin Console to Settings

- Cloud Application Manager/Getting Started/autodiscover-ec2-instances.md
@srveit 
Minor text updates
https://elasticbox.atlassian.net/browse/CAM-4438
> CAM4438-UPDATEDOC-AutoDiscoverAwsInstances-Minor Changes in texts

- Ecosystem Partners/Marketplace Guides/getting-started-with-cloudberry-lab-backup-ultimate-blueprint.md
Updated cloudberry instructions
> Updated cloudberry instructions

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
received a lot of feedback that this document is confusing. Needed to
tidy it up for MSA Certification.
> Permissions update

- Ecosystem Partners/Marketplace Guides/getting-started-with-cloudberry-lab-backup-ultimate-blueprint.md
> Fix Cloudberry Code

- General/free-trial-faq.md
Additional Sales Assistance
If you'd like to talk to a sales representative about the trial program or any pre-sales activity they can be reached as follows:
US Sales: 1.855.388.1260
UK Sales: +44 (0) 118 309 4886
> remove below - logic loop failure.

- General/free-trial-faq.md
@srveit please merge. Thanks. No JIRA story associated.
> Updated expiration

- Backup/simple-backup-service-faqs.md
> typo in backup faq

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
Fix Numbering System on sql bp kb
> Fix Numbering System on sql bp kb

- Autoscale/autoscale-faq.md
adding CentOS 6 to autoscale FAQ
> adding CentOS 6 to autoscale FAQ

- DCC Foundation/dccf-simple-backup-anywhere.md
- DCC Foundation/using-the-api.md
SBS with DCC Foundation
Using the API
> 2 new KBs for DCC Foundation

- Control Portal/user-credentials-and-logging-into-control-portal.md
PM ticket https://t3n.zendesk.com/agent/tickets/1457743
> Server Admin Credentials - out of sync password impact

- DCC Foundation/using-the-api.md
> Slight mod to verbiage

- Servers/Convert-Linux-to-repository-VMware-Tools.md
Modified vmware-uninstall-tools.pl as it wasn't clear enough for customers to follow.
> Modifying line 17 per #1466299

- Network/Azure-to-CLC-VPN-Guide.md
> Create Azure to CLC VPN guide

- Database/rdbs-deleting-instance.md
https://t3n.zendesk.com/agent/tickets/1482012
> Add clarification to deleting replicas

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
added note about default instance for MS SQL
> added note about default instance for MS SQL

- Support/supported-operating-systems.md
> Removed CentOS5 and Ubuntu 12

- Marketplace/Providers/software-as-a-service-saas-api.md
> Add delayed billing info to saas api article

- Network/intra-data-center-cross-connects-options-with-centurylink-cloud.md
Removed bullet item under 'Planning Your Cross Connect' - 'Option 2' - 'Cons'
> Remove verbiage on 20% cost if CLC orders the cross connect - 1445494

- Support/how-to-create-a-new-ban-for-subaccount.md
> Fix numbering on BAN KB

- Autoscale/autoscale-faq.md
Removed supportability for Win 2016
> Removed supportability for Win 2016

- General/centuryLink-cloud-feature-availability-matrix.md
updated relationaldb locations
> updated relationaldb locations

- Security/getting-started-with-ips.md
> updated IPS FAQ

- Security/getting-started-with-ips.md
> Fix numbering in ips guide

- Ecosystem Partners/Marketplace Guides/getting-started-with-cloudberry-lab-backup-ultimate-blueprint.md
> Our phone numbers have changed.

- Network/add-or-remove-network-interface-to-server-using-go-cli.md
PM ticket https://t3n.zendesk.com/agent/tickets/1490369
> Added note for Move Server from VLAN to VLAN

- Object Storage/object-storage-error-code-503-slow-down.md
update slow down kb with guide
> update slow down kb with guide

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
Removed noted SQL blueprint bug due to fix being pushed shortly.
> Removed noted bug due to fix

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
Updating the application type from Native to Web Application
> Update to using microsoft azure with CAM

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
Updated kb to reflect mode change for SQL
> Updated kb to reflect mode change for SQL

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-existing.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-new.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-ri.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-consolidated-billing.md
Adding a KB for RI strategy and updated partner cloud integration consolidated billing
> Adding one KB and updating another

- Managed Services/converting-unmanaged-virtual-machines-to-managed.md
- Managed Services/created-a-managed-server-now-what.md
> adding Managed Windows 2016

- Release Notes/2018/2018-02-13-cloud-platform-release-notes.md
> Release Notes 021318

- Servers/hyperscale-server-faq.md
updated hyperscale locations in kb
> updated hyperscale locations in kb

- Object Storage/object-storage-user-management.md
> Fix Numbering in OS User Mgmt

- Servers/hyperscale-server-faq.md
> Fixed typos

- Servers/platform-socket-to-vcpu-allocation.md
> Updated socket vCPU kb

- Runner/service-account.md
Fixing Format issues in runner service kb
> Fixing Format issues in runner kb

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
> added vpx v12 option

- Servers/bare-metal-faq.md
Added public ip details to bare metal faq
> Added public ip details to bare metal faq

- Blueprints/deploy-microsoft-sql-server-using-blueprint.md
Added Changelog for SQL packages
> Added Changelog for SQL packages

- Managed Services/getting-started-with-managed-mysql.md
added info about mysql instances
> added info about mysql instances

- General/centuryLink-compliance-program-availability-matrix.md
https://ctliotest.atlassian.net/browse/CP-41 | https://ctliotest.atlassian.net/browse/CTLIO-1104
> CP-41, CTLIO-1104: Create Compliance Program Availability Matrix

- Release Notes/2018/2018-03-13-cloud-platform-release-notes.md
> Format Fixes to RN

- General/centuryLink-cloud-feature-availability-matrix.md
> adding GB1 Netx

- General/centurylink-cloud-data-center-locations.md
Updated AU1 details to proper provider name
> Updated AU1 details to proper provider name

- Cloud Application Manager/Monitoring/CTLCloudMonitoringAzureSetupKB.md
Created a new Cloud Application Manager Azure Native Monitoring Configuration KB article
> CAM Azure Native Monitoring Configuration

- Release Notes/2018/2018-03-27-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/CTLIO-1118
> Release notes 032718

- Managed Services/enabling-and-disabling-managed-backup.md
Fix numbering on managed backup
> Fix numbering on managed backup

- General/free-trial-faq.md
> added language around address failure

- Servers/centurylink-cloud-guide-to-cli.md
add multiple CIDR restriction example
> add multiple CIDR restriction example

- index.md
https://ctliotest.atlassian.net/browse/CTLIO-1130
> Add Hybrid IT to index

- Network/load-balancing-comparison-matrix.md
updated NLB matrix for locations of legacy services
> update NLB matrix

- Cloud Application Manager/Managed Services/getting-started-with-cam-integration-guide.md
Cloud Application Manager/Managed Services/getting-started-with-cam-integration-guide.md
> Formatting numbered list

- Cloud Application Manager/Managed Services/Deploying-Managed-Apache.md
https://www.ctl.io/knowledge-base/cloud-application-manager/managed-services/deploying-managed-apache/
> Formatting lists

- Cloud Application Manager/Managed Services/Deploying-Managed-Tomcat.md
https://www.ctl.io/knowledge-base/cloud-application-manager/managed-services/deploying-managed-tomcat/
> Formatting ToC, numbered list

- AppFog/appfog-retirement-guide.md
Fixes to AppFog Retirement Guide
> Fixes to AppFog Retirement Guide

- AppFog/appfog-retirement-guide.md
Appfog retirement faq - one more try
> Appfog retirement faq - one more try

- Release Notes/2018/2018-05-07-cloud-platform-release-notes.md
Added line breaks between spend tiers
> updated per Chris Little's suggestion

- Managed Services/getting-started-with-managed-microsoft-sql-server.md
> updated Managed MS SQL KB

- AppFog/appfog-service-trace.md
- AppFog/blue-green-deployments.md
- AppFog/deploy-an-application.md
- AppFog/deploy-applicaton-from-ui.md
- AppFog/deploy-java-application.md
- AppFog/deploy-nodejs-application.md
- AppFog/deploy-php-application.md
- AppFog/deploy-python-application.md
- AppFog/deploy-ruby-application.md
- AppFog/deploy-static-website.md
- AppFog/deploying-a-php-laravel-application.md
- AppFog/getting-started-with-appfog.md
- AppFog/login-using-cf-cli.md
- AppFog/manage-appfog-membership.md
- AppFog/regions.md
- AppFog/setup-custom-domain-for-appfog-app.md
- AppFog/troubleshooting-application-deployment-issues.md
- AppFog/understanding-appfog-quotas.md
- AppFog/using-cloud-foundry-cli-tool.md
- AppFog/using-ctl-mysql-with-appfog-apps.md
- AppFog/using-diego.md
- AppFog/using-windows-to-deploy-your-first-application-to-appfog-step-by-step.md
https://ctliotest.atlassian.net/browse/CTLIO-1146
> [KB] AppFog EOL

- Release Notes/2018/2018-05-22-cloud-platform-release-notes.md
@jim-phillips, @JimGreene30 please consider this update before publishing RN 5/22. 
I've removed one feature that is not finally going live yet, and added an announcement that was added to the board yesterday, but not included here.
Thanks!
@rchakra1 , FYI
> Remove new Management/Application site and add CAM announcement

- Servers/vm-hardware-version-upgrade.md
KB for updating vm hardware version
> KB for updating vm hardware version

- Cloud Application Manager/Automating Deployments/managing-multi-tier-applications.md
@jim-phillips are you the one who typically review this kind of changes?
> [CAM KB] Fix tags in bindings sample

- Cloud Application Manager/Deploying Anywhere/using-azure.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
> Fix Azure articles

- Cloud Application Manager/Automating Deployments/version-control.md
> Add link to publish box tutorial

- Cloud Application Manager/Integrating with Jenkins/jenkins-cloud-application-manager-slaves.md
- Cloud Application Manager/Tutorials/vagrant-dev-environment-tutorial.md
> Fix CAM tutorials

- Cloud Application Manager/Getting Started/TAM-Support-Engagement.md
Added KB per Jeff Martin's request
> New TAM Support Engagement KB

- Support/change-management.md
Added network change policy and fixed a typo in previous content
> Add network change policy/ fix typo

- Managed Services/mdrs-AD-DR.md
add MDRS AD replication FAQ article
> add MDRS AD replication FAQ article

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
https://ctliotest.atlassian.net/browse/CTLIO-1245
> [KB] fix formatting, edit grammar

- Servers/hyperscale-eol-faqs.md
Item #5 in https://ctliotest.atlassian.net/browse/CTLIO-1250.
Needs to deploy in conjunction with https://ctliotest.atlassian.net/browse/CP-93
> Hyperscale faq

- Servers/hyperscale-eol-faqs.md
Corrected EOL date - should be aug 21
> Corrected EOL date - should be aug 21

- Servers/vm-hardware-version-upgrade.md
> Removed sticky

- Network/connecting-data-center-networks-through-firewall-policies.md
> fix numbering

- General/centurylink-cloud-data-center-locations.md
> updated vendor name

- General/outbound-email-protocol.md
@jim-phillips please merge for next deployment. No Jira story for this.
> Update to new protocols

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
> fixed key length

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
@julianatienza, @GustavoLlorente, 👍 ?
> Add point 7 to explain the required pemissions for temporal user creation

- Servers/self-service-vm-import-ovf-requirements.md
Added new section to stipulate interface naming convention requirements for CentOS.
> Add CentOS interface naming requirement

- Cloud Application Manager/Deploying Anywhere/using-azure.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
@GustavoLlorente, @dsimon1992 could you please review? Thanks!
> Update Azure articles with Table of Contents and working links 

- Cloud Application Manager/Billing/billing-menu.md
- Cloud Application Manager/Billing/billing-separate-invoices.md
> Add ToC, Overview, Audience and Prereqs sections and fix link in Billing section

- Cloud Application Manager/Automating Deployments/running-code-outside-an-instance.md
> Extend task variables KB with 2 new task events.

- Cloud Application Manager/Getting Started/autodiscover-ec2-instances.md
Add ToC and types of instances you can register to include CF deployed instances and auto scaling groups.
@rchakra1, @EfrenRey, @davisein, 👍?
> Add ToC and include CF deployed instances and auto scaling groups as registrable instances

- Release Notes/2018/2018-08-07-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/CTLIO-1341
> [KB] Release notes 080718

- Release Notes/2018/2018-08-07-cloud-platform-release-notes.md
> [KB] Release notes for 8/7

- General/Authentication/enhanced-security-common-issues-and-frequently-asked-questions.md
I am updating the KB with more email troubleshooting instructions.  I am also updating the support contact procedures.
> Updating KB

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
@jim-phillips, Would you mind to review and merge? Thanks!
@gsanchezu Ey Guillermo. This is the update I commented you in Jira Ticket.
> Update for the required pemissions in Azure temporal user creation

- General/CenturyLinkCloud/centurylink-cloud-data-center-locations.md
https://ctliotest.atlassian.net/browse/PE-1347
> revised data center language

- Network/load-balancing-dedicated-vs-shared.md
Essentially copied the support agreement from https://www.ctl.io/knowledge-base/network/load-balancing-comparison-matrix/
> Clarified support for Dedicated Load balancers

- General/Authentication/enhanced-security-common-issues-and-frequently-asked-questions.md
... and consistent capitalization of Master Account.
https://ctliotest.atlassian.net/browse/PE-1364
> formatting changes

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
@gsanchezu Please, can you review new Doc. with me before to ask for merge? Thanks in advance!
> For BYOC Azure accounts the powershell script is needed to allow automatically deletion of temporal users

- Release Notes/2018/2018-09-18-cloud-platform-release-notes.md
> Release Notes for 0918

- Object Storage/using-object-storage-via-rest-api-aws-sdk.md
Adding a section with example code on how to configure the aws java sdk to talk to clc object storage.
> update object storage sdk article

- Disaster Recovery/SafeHaven 5 CLC to AWS/Create CMS in AWS.md
Added a few comments to the instructions.
> Update Create CMS in AWS.md

- Disaster Recovery/SafeHaven 5 CLC to AWS/Create DR SRN in AWS.md
Added a few comments to the instructions.
> Update Create DR SRN in AWS.md

- Disaster Recovery/SafeHaven 5 CLC to AWS/Register Datacenters within a SafeHaven Console.md
Enhanced documentation to reflect changes in the SafeHaven console.
> Update Register Datacenters within a SafeHaven Console.md

- Disaster Recovery/SafeHaven 5 CLC to AWS/Register SRN within SafeHaven Console.md
> Update Register SRN within SafeHaven Console.md

- Disaster Recovery/SafeHaven 5 CLC to AWS/Test Failover to AWS.md
> Update Test Failover to AWS.md

- Marketplace/Providers/software-as-a-service-saas-api.md
https://ctliotest.atlassian.net/browse/PE-1432
> update example payload to include alias and email

- Network/add-or-remove-network-interface-to-server-using-go-cli.md
Added a line to specify "Note: Only one vNIC per VLAN is permitted."
> Update stating "Note: Only one vNIC per VLAN is permited."

- Object Storage/introducing-object-storage.md
- include a link to available regions
- remove wording that says users operate per-region
- fix grammatical error in question for what people can do in control
> update Object Storage introduction

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
> Fix indentation to continue numbered list

- Cloud Application Manager/Analytics/AdvancedAnalyticsAccess.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
Update to Hardening KB and Analytics Permissions Change
> Update to Hardening KB and Analytics Permissions Change

- Cloud Application Manager/Core Concepts/workspaces-and-collaboration.md
> Add provider visibility to workspace viewer role description

- Cloud Application Manager/Core Concepts/boxes.md
> [CAM-8427] Boxes KB Documentation

- Cloud Application Manager/Core Concepts/providers.md
Review CAM Management > Providers KB documentation and update it accordingly
Update providers table.
Updated metadata.
Included intro sections Table of Contents, overview, audience prerequisites (TCOAP).
Minor markdown fixes.
Please review @gsanchezu
> [CAM-8425] Review CAM Management > Providers

- managed-exchange-sharepoint-eol-faqs.md
https://ctliotest.atlassian.net/browse/PE-1473
> [KB] Managed Exchange EOL FAQs

- Cloud Application Manager/Tutorials/vagrant-dev-environment-tutorial.md
- Disaster Recovery/SafeHaven 5 CLC to AWS/Gather Production Server Information.md
- Disaster Recovery/SafeHaven 5 CLC to AWS/Install Scripts and Start Replication for Linux Protection Group.md
- Disaster Recovery/SafeHaven 5 CLC to Azure/CreateCMSAzure.md
- Disaster Recovery/SafeHaven 5 CLC to Azure/CreateDRSRNAzure.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Install-Scripts-for-Linux-ph-clc-clc.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Test-Failover-to-CLC.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/configure-recovery-server-linux-clc-clc.md
- Disaster Recovery/SafeHaven 5 CPC-vCF to CLC/configure-recovery-server-linux.md
- Disaster Recovery/SafeHaven 5 CPC-vCF to CLC/test-failover-dccf-clc.md
This refers to https://github.com/CenturyLinkCloud/sh-safehaven3/issues/4246
> Spelling errors

- Network/creating-a-self-service-ipsec-site-to-site-vpn-tunnel.md
CLC MIB-887 https://t3n.zendesk.com/agent/tickets/1567701
> Add IKEv2 and Redundant VPN to non-standard VPNs

- CenturyLink Private Cloud on VMware Cloud Foundation/cam-provider.md
> [KB] Update cam-provider.md

- General/Hybrid IT/using-estimator-spreadsheet.md
> added a link

- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
@SergioQCL I documented your latest improvement to the instances search field. Could you please review?
> Add search field description and searchable fields

- Release Notes/2018/2018-11-27-cloud-platform-release-notes.md
@jim-phillips could you please review an merge? Thanks!
> Minor wording fixes

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-hardening-permissions.md
Updated variable for Customer Group
> Updated variable for Customer Group

- Cloud Application Manager/Automating Deployments/google-deployment-manager.md
@DenesPal, FYI. The line breaks were appearing in the published article, so I removed them and make minor adjustments. Please, review.
> FIx article line splits

- Servers/resizing-disks-in-linux-virtual-machines.md
Added a hyperlink at the end to a KB that details expanding file system in the Linux Operating system.
> Add hyperlink to a second KB that explains the OS level changes

- Cloud Application Manager/Getting Started/autodiscover-ec2-instances.md
Changed to [Register an Existing Instance](./register-existing-instance.md)
> Fixed broken link to another KB

- Backup/simple-backup-service-faqs.md
We have a process for this. Updating this entry to point customers to the relevant KB article.
> Restoring to alternate server.

- Backup/simple-backup-service-faqs.md
Adding a reference to Reports kb in these sections so customers know they can perform some troubleshooting steps.
> Adding to Backups and Restores sections

- Network/creating-a-self-service-load-balancing-configuration.md
Changing persistence from standard to none and from "sticky" to Source Ip to reflect what is displayed in control.
> Update to KB

- Servers/creating-a-new-enterprise-cloud-server.md
Updating KB to reflect that CTL provides default DNS and their IP's.
> Adding default DNS servers

- Servers/bare-metal-faq.md
Publicly stating that Blueprint functionality is not supported for Bare Metal servers.
> Adding update regarding Blueprints

- Cloud Application Manager/Managed Services/getting-started-with-cam-integration-guide.md
Updated verbiage about check catalog within the Create Monitoring Policy section of the KB.
> Updated verbiage about Check Catalog

- Release Notes/2019/2019-01-22-cloud-platform-release-notes .md
> Release notes 0122

- Cloud Application Manager/Automating Deployments/arm-template-box.md
- Cloud Application Manager/Automating Deployments/aws-template-box.md
- Cloud Application Manager/Automating Deployments/google-deployment-manager.md
- Cloud Application Manager/Automating Deployments/template-box.md
- Cloud Application Manager/Automating Deployments/terraform-template-box.md
> Update template boxes articles title

- Servers/cloning-best-practices.md
Added bullet point directing users to the Required ports for Control functionality kb.
> Ports for Control functionality

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
- Cloud Application Manager/Getting Started/register-existing-aws-linux-instance.md
- Cloud Application Manager/Getting Started/register-existing-aws-windows-instance.md
- Cloud Application Manager/Getting Started/register-existing-instance.md
> Add public IP requirement and rewording

- Control Portal/using-saml-for-single-sign-on-to-the-centurylink-platform-control-portal.md
Removed the old certificate and updated with the new certificate.
> Update SAML Sign in certificate

- Managed Services/getting-started-with-managed-microsoft-sql-server.md
Fixing the article to better represent our supported versions and editions of MSSQL.
https://t3n.zendesk.com/agent/tickets/1583847
> Fixing articles multiple discrepencies

- Service Tasks/deploy-a-dedicated-citrix-vpx-appliance.md
12.1 supports vmotion and is released.
> Updated versions to include latest 12.1 release

- Network/centurylink-cloud-ids-idp-platform-faq.md
"DDoS" linked to an old page on centurylink.com that no longer exists.
> Revised DDoS Link

- Cloud Application Manager/Analytics/CloudApplicationManagerAnalyticsAWSSetup.md
Taking this out because the bucket is now invalid.
You can inspect the code snippet [here](https://s3.us-east-2.amazonaws.com/ctl-cloudoptimization/CTLCloudOptimizationIAMPolicy.template.json).
> Removed Code Snippet

- Release Notes/2019/2019-02-19-cloud-platform-release-notes.md
Hey @jim-phillips, @dstephanCTL, I added a note that was not included in yesterday's PR.
> Add terminate and shutdown protection note

- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
@gsanchezu, please review my PR
> Add description of instance state

- Cloud Application Manager/Deploying Anywhere/kubernetes.md
@DenesPal these styles didn't look good when published, so I changed them
> Fix MD styles

- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
> Fix title link and minor MD style changes

- Release Notes/2019/2019-03-05-cloud-platform-release-notes.md
@jgerger, @jim-phillips, please review. It should be merged before publishing it today
> Fix title and remove GA item

- Cloud Application Manager/Automating Deployments/google-deployment-manager.md
- Cloud Application Manager/Automating Deployments/parameterizing-boxes-with-variables.md
- Cloud Application Manager/Automating Deployments/syntax-for-variables.md
- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
- Cloud Application Manager/Managed Services/getting-started-with-cam-integration-guide.md
> Remove code block language

- Release Notes/2019/2019-03-05-cloud-platform-release-notes.md
> Minor RN syntax fixes

- Cloud Application Manager/Automating Deployments/using-kubernetes.md
Behaviour will change with CAM-10280
@gsanchezu please review
> CAM-10103 patch-1

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
Added documentation related to detail instance information. 
Removed language indicators in the code inserted to prevent the black background, as @gsanchezu indication. 
Please review @davisein @gsanchezu, thank you!
> [CAM-10225] Write documentation of direct link to AWS instances

- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
@gsanchezu Do you agree?
Thanks!
> Include description of all action taken wen we deploy instances with ARM Templates in MSA providers

- Release Notes/2019/2019-04-02-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1727
> [KB] Release notes for 4/2

- Cloud Application Manager/Troubleshooting/troubleshooting-tips.md
corrected grammar errors and added proxy tips. @gsanchezu please review
> corrected grammar errors and added proxy tip

- Release Notes/2019/2019-04-16-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1753
> [KB] Release Notes 4/16/19

- Servers/centurylink-cloud-backup-and-recovery-services.md
Updating per https://t3n.zendesk.com/agent/tickets/1610959
> Add support for Windows 2016

- Cloud Application Manager/Analytics/CloudApplicationManagerAnalyticsAWSSetup-Manual.md
> Updated Policy

- Release Notes/2019/2019-05-07-cloud-platform-release-notes.md
@jim-phillips or @asanokhin, please review and include this one for today's push. Thanks
> Update 2019-5-7 release notes

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-existing.md
> Cost Center Admin

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
> Including some AWS Console access logging information

- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
> Added section to explain CAM abort operation feature

- Cloud Application Manager/Automating Deployments/application-box.md
- Cloud Application Manager/Automating Deployments/deploymentpolicy-box.md
- Add section about claims in deploymentpolicy-box
- Add reference about claims in application-box
> CAM-11113 - Claims and Requirements

- Release Notes/2019/2019-05-07-cloud-platform-release-notes.md
For some reason this did not contain the release note from https://trello.com/c/O0Gx6sy2/4-cloud-application-manager
> Text change

- Cloud Application Manager/Automating Deployments/arm-template-box.md
- Cloud Application Manager/Automating Deployments/aws-template-box.md
- Cloud Application Manager/Automating Deployments/managing-multi-tier-applications-with-bindings.md
- Cloud Application Manager/Automating Deployments/parameterizing-boxes-with-variables.md
- Cloud Application Manager/Core Concepts/catalog.md
- Cloud Application Manager/Core Concepts/workspaces-and-collaboration.md
- Cloud Application Manager/Deploying Anywhere/deploying-on-anyinfra.md
- Cloud Application Manager/Deploying Anywhere/using-azure.md
- Cloud Application Manager/FAQ/FAQ.md
- Cloud Application Manager/Tutorials/binding-examples.md
> Minor updates and fixes for Cloud Academy

- Cloud Application Manager/Billing/billing-menu.md
Cloud Academy: review documentation explaining CAM billing Dashboard and Usage History
@gsanchezu
> [CAM-11110] Cloud Academy: review documentation explaining CAM billing Dashboard and Usage History

- Cloud Application Manager/Core Concepts/providers.md
> [CAM-11111] provider synchronization process details

- Release Notes/2019/2019-05-28-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1798
> [KB] Release notes for 5/28

- Release Notes/2019/2019-06-11-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1819
> [KB] Release notes for 6/11

- CenturyLink Private Cloud on VMware Cloud Foundation/Support/getting-support.md
Adding Latin America support email and phone numbers
https://ctliotest.atlassian.net/browse/PE-1818
> [KB] Update getting-support.md

- Cloud Application Manager/Deploying Anywhere/using-the-vmware-vcenter-private-datacenter.md
CAM vCenter FIX: TOC, author, supported versions
Please review @gsanchezu
> CAM vCenter FIX: TOC, author, supported versions

- Managed Services/created-a-managed-server-now-what.md
Updated the time to complete from 60 minutes to 2 hours for the make managed process to complete.
> Updated time to complete

- Managed Services/converting-unmanaged-virtual-machines-to-managed.md
Updated the time to completion from 60 minutes to 2 hours for the process to complete
> 2 hours for make managed

- Release Notes/2019/2019-06-25-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1855
> [KB] Release notes for 6/25

- Cloud Application Manager/Automating Deployments/template-box.md
- Cloud Application Manager/Automating Deployments/terraform-template-box.md
@gsanchezu please review. Thanks.
> CAM Terrafrom supports 2 additional providers

- dedicated-switch-juniper-ex4500-eol-faq.md
- managed-load-balancer-f5-big-ip-1600-3600-eol-faq.md
https://ctliotest.atlassian.net/browse/PE-1863
> [KB] FAQ for EOL Dedicated Switch and Managed LB for 7/2

- Release Notes/2019/2019-0709-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1876
> [KB] Release notes for 7/9

- Servers/creating-a-new-enterprise-cloud-server.md
Update to advise that password mismatch will affect cloning and other automation.  Will affect domain controllers as well.
> Update to advise that password mismatch

- Release Notes/2019/2019-07-23-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1905
> [KB] Release notes for 7/23

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-deleteCustomerAccount.md
new Microsoft requirements for deletes
> new Microsoft requirements for deletes

- dco-program-faq.md
New hidden KB --  no folder so it won't show up in the KB directory
https://ctliotest.atlassian.net/browse/PE-1935
> [CTL] DCO Program FAQs for 8/1

- Cloud Application Manager/Core Concepts/providers.md
https://ctliotest.atlassian.net/browse/PE-1939
> [CTL] Fixing broken links

- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
> Remove the roles and permissions section, that only applies to resale

- Release Notes/2019/2019-08-06-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-1948
> [KB] Release notes for 8/6

- Disaster Recovery/SafeHaven 5 CLC to CLC/Check Replication Status.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Configure Checkpoints.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Configure Email Alerts.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Create SafeHaven Cluster and Login to SafeHaven Console.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Create-manual-checkpoint-clc-clc.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Install-Scripts-for-Linux-ph-clc-clc.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/Modify WAN Replication Rate.md
- Disaster Recovery/SafeHaven 5 CLC to CLC/add-srn-peers-clc-clc.md
- Disaster Recovery/SafeHaven 5 CPC-vCF to CLC/configure-recovery-server-linux.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-logicnow-backup-recovery.md
https://ctliotest.atlassian.net/browse/PE-1955
> [CTL] Remove non-working video embeds

- General/CenturyLinkCloud/free-trial-faq.md
https://ctliotest.atlassian.net/browse/PE-1872
merge w/ https://github.com/CenturyLinkCloud/PublicPlatform/pull/3400
> [KB] Latam modifications for Self-Sign Up FAQ

- whitelisting-best-practices
per https://t3n.zendesk.com/agent/tickets/1647138
> Add whitelist KB

- Cloud Application Manager/Automating Deployments/arm-template-box.md
- Cloud Application Manager/Automating Deployments/managing-multi-tier-applications-with-bindings.md
- Cloud Application Manager/Core Concepts/workspaces-and-collaboration.md
- Cloud Application Manager/Deploying Anywhere/using-openstack-cloud.md
- Cloud Application Manager/Getting Started/application-deployment.md
- Cloud Application Manager/Integrating with Jenkins/jenkins-cloud-application-manager-slaves.md
https://ctliotest.atlassian.net/browse/PE-1982
> [KB] CAM Guides Consolidation

- Cloud Application Manager/Administering Your Organization/resource-tags.md
- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
> Fix AWS Role ARN and add Origin tag

- Cloud Application Manager/Troubleshooting/camdce-troubleshooting-tips.md
- Cloud Application Manager/Troubleshooting/troubleshooting-tips.md
Split appliance tips in a separate article, change order in some cases and add registering troubleshooting.
@thomasbroadwell, @DiegoSanjuan, @juanmorra, 👍 ?
> Split appliance tips, reorder and add registering troubleshooting

- Release Notes/2019/2019-10-01-cloud-platform-release-notes.md
> update Release notes

- Servers/centurylink-cloud-backup-and-recovery-services.md
https://ctliotest.atlassian.net/browse/PE-2026
> [KB] Revise CLC Backup & Recovery Services Matrix

- Servers/Self-Service-Updates-of-VMware-Tools.md
old link: https://packages.vmware.com/tools/releases/latest/windows/x64/index.html
updated link: https://packages.vmware.com/tools/esx/latest/windows/x64/index.html
> Update of Windows vmware tools download link

- Network/dedicated-load-balancer-license-management.md
https://ctliotest.atlassian.net/browse/PE-2042
> [KB] Format Fix on LB License Mgmt article

- Managed Services/managed-operating-system-frequently-asked-questions.md
https://ctliotest.atlassian.net/browse/PE-2046
> Update to remove CNS acronym

- Release Notes/2019/2019-10-15-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-2047
> [KB] Release Notes for 10/15

- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
- Cloud Application Manager/Getting Started/register-existing-google-cloud-instance.md
> Fix CAM Google Cloud doc for instance protection, register and self-register

- Cloud Application Manager/Core Concepts/architecture-components.md
> Fix ToC and lint errors

- Managed Services/getting-started-with-managed-microsoft-iis.md
- Managed Services/managed-backup-frequently-asked-questions.md
- Managed Services/managed-operating-system-frequently-asked-questions.md
- Managed Services/managed-os-operating-system-patching-and-update-processes.md
https://ctliotest.atlassian.net/browse/PE-2058
> [KB] Managed Services KB Updates

- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-leaving.md
Removed any mention of customer contacting AWS
> Removed any mention of customer contacting AWS

- Cloud Application Manager/Automating Deployments/arm-template-box.md
- Cloud Application Manager/Automating Deployments/aws-template-box.md
- Cloud Application Manager/Automating Deployments/template-box.md
- Cloud Application Manager/Automating Deployments/terraform-template-box.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
> Add auto-register section to the supporting template box articles

- Release Notes/2019/2019-11-12-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-2094
> [KB] Release Notes for 11/12

- Cloud Application Manager/Core Concepts/architecture-components.md
Updated Watcher agent section to detail the secure mechanisms used for Watcher communication to SaaS environment
> Add secure comm for Watcher

- Cloud Application Manager/Core Concepts/providers.md
> Fix CPC provider link

- Release Notes/2019/2019-11-12-cloud-platform-release-notes.md
> Update auto-register Terraform paragraph

- Object Storage/using-object-storage-from-the-control-portal.md
Added short section "Delete Object Storage buckets"
> Added section on bucket deletion 1652595.

- Cloud Application Manager/Deploying Anywhere/deploying-on-anyinfra.md
- Cloud Application Manager/Deploying Anywhere/using-compute-instances.md
> Add keywords, fix alternate texts and move preferred paragraph to BYOI

- translation-ux.md
https://ctliotest.atlassian.net/browse/PE-2126
No folder is correct per Lyza, for 11/26-12/10 sprint
> [KB] Translation UX Article

- Cloud Application Manager/Automating Deployments/application-box.md
- Cloud Application Manager/Automating Deployments/deploymentpolicy-box.md
- Cloud Application Manager/Automating Deployments/parameterizing-boxes-with-variables.md
- Cloud Application Manager/Automating Deployments/script-box.md
- Cloud Application Manager/Automating Deployments/template-box.md
- Cloud Application Manager/Automating Deployments/version-control.md
- Cloud Application Manager/Core Concepts/architecture-components.md
- Cloud Application Manager/Core Concepts/context-switcher.md
- Cloud Application Manager/Deploying Anywhere/deploying-managing-instances.md
- Cloud Application Manager/Deploying Anywhere/kubernetes.md
- Cloud Application Manager/Deploying Anywhere/using-centurylink-cloud.md
- Cloud Application Manager/Deploying Anywhere/using-microsoft-azure.md
- Cloud Application Manager/Deploying Anywhere/using-private-cloud-on-vmware-cloud-foundation.md
- Cloud Application Manager/Deploying Anywhere/using-your-aws-account.md
- Cloud Application Manager/Getting Started/register-existing-instance.md
- Cloud Application Manager/Troubleshooting/troubleshooting-tips.md
- Cloud Application Manager/Tutorials/ebcli-tutorial.md
- Cloud Application Manager/Tutorials/jenkins-ci-cd-tutorial.md
- Cloud Application Manager/Tutorials/lamp-stack-tutorial.md
> Add sticky flag to some articles and fix markdown-lint issues

- Cloud Application Manager/Billing/billing-menu.md
@EfrenRey, could you please review? Minor changes, nothing really affecting billing simplification
> Review and minor updates for billing simplification

- Release Notes/2019/2019-12-03-cloud-platform-release-notes.md
Creating the pull request in advance so that it can be merged EOD Friday
> Cloud Platform Release Notes - Dec 3

- Release Notes/2019/2019-12-03-cloud-platform-release-notes.md
Hey @AroraAnshul, @jim-phillips, @JimGreene30, updating one item as requested by Product Management. Could you please review and merge before publishing? Thanks!
> Update to billing simplification RN

- Release Notes/2019/2019-12-17-cloud-platform-release-notes.md
https://ctliotest.atlassian.net/browse/PE-2159
> [KB] Release notes for 12/17

- Release Notes/2019/2019-12-17-cloud-platform-release-notes.md
Also, update of the disconnect one.
@jim-phillips, @JimGreene30, 👍 ?
> Add user-defined DC and networks to 12-17 RN

- Network/load-balancing-comparison-matrix.md
https://t3n.zendesk.com/agent/tickets/1661444
> Remove reference to Legacy LBaaS

- Cloud Application Manager/Deploying Anywhere/orchestrating-vcloud-air-vcloud-director-deployments.md
- Cloud Application Manager/Deploying Anywhere/using-private-cloud-on-vmware-cloud-foundation.md
> Add VMWare tools prereqs to CPC KB

- Network/network-exchange-iq-plus-endpoint-guide.md
- dco-program-faqs.md
https://ctliotest.atlassian.net/browse/PE-2122
> [KB] Updates to Data Center References on CTL.io

- Cloud Application Manager/Core Concepts/context-switcher.md
- Cloud Application Manager/Core Concepts/workspaces-and-collaboration.md
> Move personal vs team workspaces explanation to wks KB and add more titles

- Cloud Application Manager/Deploying Anywhere/Using-CenturyLink-Private-Cloud-with-VMC-on-AWS.md
- Cloud Application Manager/Deploying Anywhere/using-the-vmware-vcenter-private-datacenter.md
@jinzishuai, FYI.
Just minor pending PR comment fixes and fix the broken link (I also got ownership of the article, 😉 )
> Fix pending PR comments and broken link

- index.md
updating KB index: https://ctliotest.atlassian.net/browse/PE-2132
> [KB] Storage Section

- Release Notes/2020/2020-01-14-cloud-platform-release-notes.md
Please merge as soon as possible as the existing release notes for 1/14/20 are incorrect.
> Corrected 01/14/2020 Release Notes

- Release Notes/2020/2020-01-14-cloud-platform-release-notes.md
Add links, fix typo and remove some trailing spaces. @thomasbroadwell, 👍 ?
> Add links to section titles

- Release Notes/2020/2020-02-04-cloud-platform-release-notes.md
Hey @bjswoboda, I fixed some titles and links (some titles were too tiny, so I removed one level to better align with what we typically do)
👍 ?
> Fix titles and links

- Cloud Application Manager/Administering Your Organization/admin-overview.md
- Release Notes/2017/2017-05-09-cloud-platform-release-notes.md
- Servers/bare-metal-faq.md
- Storage/Object Storage/object-storage-3rd-party-compatibility.md
https://ctl.atlassian.net/browse/BILL-1334
> PETS Site Maintenance: Site Map, Broken Links and Lint Errors

- Release Notes/2020/2020-03-03-cloud-platform-release-notes.md
https://ctl.atlassian.net/browse/BILL-1432
> [KB] Release notes for 3/3/20

- Release Notes/2020/2020-03-03-cloud-platform-release-notes.md
Hey @jim-phillips, @JimGreene30, could you please take a look at this one before publishing the RN? Thanks!
> Update language for ALM agent as non-root announcement

- Release Notes/2020/2020-01-28-cloud-platform-release-notes.md
- Release Notes/2020/2020-03-17-cloud-platform-release-notes.md
@jim-phillips, @JimGreene30, 👍?
> Add Release Notes 3/17

- Cloud Application Manager/Getting Started/register-existing-instance.md
- Cloud Application Manager/Getting Started/self-register-instances.md
> Add self-register restart consideration for CPC/VCD providers

- Network/CenturyLink Cloud/Azure-to-CLC-VPN-Guide.md
https://t3n.zendesk.com/agent/tickets/1672416
> Add link to CLC VPN KB

- Servers/creating-a-new-enterprise-cloud-server.md
Update made for https://t3n.zendesk.com/agent/tickets/1669115
> Update regarding under construction servers

- Release Notes/2020/2020-03-31-cloud-platform-release-notes.md
https://ctl.atlassian.net/browse/BILL-1609
> [KB] Release notes for 3/31

- Release Notes/2020/2020-03-31-cloud-platform-release-notes.md
fix the date
https://ctl.atlassian.net/browse/BILL-1609
> PETS [KB] Release notes for 3/31

- Release Notes/2020/2020-04-14-cloud-platform-release-notes.md
https://ctl.atlassian.net/browse/BILL-1652
> [KB] Release notes for 4/14

- Servers/getting-started-how-to-securely-connect-to-your-server.md
ZD: https://t3n.zendesk.com/agent/tickets/1672146
> Adding instructions for linux

- Servers/using-stonith-fencing-agent-with-centurylink-cloud.md
https://ctl.atlassian.net/browse/BILL-1693
> [KB] STONITH Fencing Agent article

- Release Notes/2020/2020-04-28-cloud-platform-release-notes.md
https://ctl.atlassian.net/browse/BILL-1761
> PETS [KB] Release notes for 4/28

- translation-ux.md
adding anchor tags: https://ctl.atlassian.net/browse/BILL-1779
> [KB] Site Translation Scope

- Release Notes/2020/2020-04-28-cloud-platform-release-notes.md
Hey @JimGreene30, I realized it would be best to put the first one into announcements.
Could you please review update? Thanks!
> Split enhancements into announcements and enhancements

- Support/unactionable-issues-reported.md
https://ctl.atlassian.net/browse/BILL-1801
> [KB] Unactionable Issues article

- Support/public-ip-migration-faqs.md
Per https://t3n.zendesk.com/agent/tickets/1684311
> New Public IP Migration KB

- Storage/CenturyLink Network Storage/glossary-of-terms.md
https://ctl.atlassian.net/browse/BILL-1917
> [KB] CNS Glossary

- Network/Content Delivery Network/contacting-cdn-support.md
https://ctl.atlassian.net/browse/BILL-1966
> [KB] Document Support for CDN products

- Storage/CenturyLink Network Storage/centurylink-customer-responsibilities.md
https://ctl.atlassian.net/browse/BILL-1969
> [KB] CenturyLink and Customer Responsibilities for CNS

- Support/public-ip-migration-faqs.md
https://t3n.zendesk.com/agent/tickets/1688060
> API IP config migration steps

- Release Notes/2020/2020-06-23-cloud-platform-release-notes .md
https://ctl.atlassian.net/browse/BILL-3015
> [KB] Release notes for 6/23

- General/CenturyLinkCloud/account-activation-faqs.md
https://ctl.atlassian.net/browse/BILL-3055
> [KB] Revise Free Trial KB

- translation-ux.md
https://ctl.atlassian.net/browse/BILL-3097
> [KB] Revised Translation KB for 6/30

- Backup/automating-sbs-on-api-v2.md
- Backup/backup-anywhere-manual-install.md
- Backup/backup-anywhere.md
- Backup/getting-started-with-simple-backup.md
- Backup/linux-rdp.md
- Backup/removing-simple-backup-service.md
- Backup/reports.md
- Backup/restarting-simple-backup-service.md
- Backup/restore-to-alternate-server.md
- Backup/restores.md
- Backup/sbs-agent-security.md
- Backup/sbs-backing-up-databases.md
- Backup/sbs-monitoring.md
- Backup/simple-backup-service-faqs.md
- Backup/simple-backup-service-how-it-works.md
- Backup/webhooks.md
https://ctl.atlassian.net/browse/BILL-3145
> [KB] Keywords: Backup

- Storage/CenturyLink Network Storage/centurylink-customer-responsibilities.md
- Storage/CenturyLink Network Storage/getting-started-creating-cns-nodes-volumes.md
- Storage/CenturyLink Network Storage/glossary-of-terms.md
- Storage/Object Storage/introducing-object-storage.md
- Storage/Object Storage/object-storage-3rd-party-compatibility.md
- Storage/Object Storage/object-storage-error-code-503-slow-down.md
- Storage/Object Storage/object-storage-regions-and-service-points.md
- Storage/Object Storage/object-storage-user-management.md
- Storage/Object Storage/request-rate-and-performance-considerations.md
- Storage/Object Storage/s3cmd-object-storage-management-for-linux-machines.md
- Storage/Object Storage/temporary-request-redirection.md
- Storage/Object Storage/using-object-storage-for-backup-as-a-service.md
- Storage/Object Storage/using-object-storage-from-3rd-party-tools.md
- Storage/Object Storage/using-object-storage-from-the-control-portal.md
- Storage/Object Storage/using-object-storage-via-rest-api-aws-sdk.md
- Storage/Object Storage/using-object-storage-with-a-cloud-storage-gateway.md
https://ctl.atlassian.net/browse/BILL-3144
> [KB] Keywords: Storage

- Database/rdbs-backups-and-restores.md
- Database/rdbs-deleting-instance.md
- Database/rdbs-mssql-getting-started.md
- Database/rdbs-mssql-replication-and-failover.md
- Database/rdbs-mysql-configuration-profiles.md
- Database/rdbs-mysql-connecting-over-ssl.md
- Database/rdbs-mysql-connecting-through-mysql-client.md
- Database/rdbs-mysql-faqs.md
- Database/rdbs-mysql-getting-started.md
- Database/rdbs-mysql-replication-and-failover.md
- Database/rdbs-resizing-instance.md
- Database/rdbs-sign-up-for-usage-alerts.md
https://ctl.atlassian.net/browse/BILL-3143
> [KB] Keywords: Database

- Network/Content Delivery Network/cdn-mesh-delivery-capabilities.md
- Network/Content Delivery Network/cdn-mesh-delivery-how-it-works.md
- Network/Content Delivery Network/contacting-cdn-support.md
- Network/Network Exchange/network-exchange-billing-guide.md
- Network/Network Exchange/network-exchange-centurylink-private-cloud-endpoint-guide.md
- Network/Network Exchange/network-exchange-clc-colocation-endpoint-guide.md
- Network/Network Exchange/network-exchange-clc-dedicated-access-endpoint-guide.md
- Network/Network Exchange/network-exchange-clc-endpoint-guide.md
- Network/Network Exchange/network-exchange-clc-managed-hosting-endpoint-guide.md
- Network/Network Exchange/network-exchange-connectivity-matrix-configuration-guide.md
- Network/Network Exchange/network-exchange-faqs.md
- Network/Network Exchange/network-exchange-feature-requests.md
- Network/Network Exchange/network-exchange-getting-started-guide.md
- Network/Network Exchange/network-exchange-iq-plus-endpoint-guide.md
- Network/Network Exchange/network-exchange-support-guide.md
https://ctl.atlassian.net/browse/BILL-3148
> [KB] Keywords Network Exchange & CDN

- General/CenturyLinkCloud/account-activation-faqs.md
https://ctl.atlassian.net/browse/BILL-3151
> [KB] Fix Trial Account FAQ

- CenturyLink Private Cloud on VMware Cloud Foundation/API/using-the-api.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Administration/adding-org-admin.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Administration/change-user-password.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Backup/simple-backup-anywhere.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Catalog/add-to-catalog-flex.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Catalog/add-to-catalog.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Catalog/default-catalog.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Firewall/dfw-enabling-flex.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Firewall/dfw-enabling.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Firewall/dfw-same-network-flex.md
- CenturyLink Private Cloud on VMware Cloud Foundation/Firewall/dfw-same-network.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/cam-provider.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/change-password.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/core-concepts.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/cpc-metrics.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/creating-a-server-flex.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/creating-a-server.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/faq.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/glossary-of-terms.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/monitoring.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/vcd-prerequisites.md
- CenturyLink Private Cloud on VMware Cloud Foundation/General/windows-2019.md
Sections Admin-General: https://ctl.atlassian.net/browse/BILL-3135
> [KB] Keywords CPC 

- General/CenturyLinkCloud/account-activation-faqs.md
Not tied to a story. Please merge.
> minor edit to remove free reference

- Servers/creating-and-managing-server-snapshots.md
> Snapshots not available for VPX load balancers

- Network/Lumen Cloud/Lumen-Cloud-Guide-to-Cohesive-VNS3-Network-Appliance.md
> Fixed LumenLumenLumen

- Backup/restore-to-alternate-server.md
- Cloud Application Manager/Analytics/CloudApplicationManagerAnalyticsAWSSetup-Manual.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-deleteCustomerAccount.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-aws-new.md
- Cloud Application Manager/Cloud Optimization/partner-cloud-integration-azure-deleteCustomerAccount.md
- Dedicated Cloud Compute/Getting Started/dcc-glossary-of-terms.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-avni-software-defined-cloud-partner-template.md
- Ecosystem Partners/Marketplace Guides/getting-started-with-oracle-jdk-on-windows.md
- Managed Services/mdrs-AD-DR.md
- Network/Network Exchange/network-exchange-getting-started-guide.md
- Release Notes/2016/2016-12-05-cloud-platform-release-notes.md
- Support/windows-2008-end-of-vendor-support-faq.md
- dco-program-faqs.md
https://ctl.atlassian.net/browse/ECLDE-3026
> Updating ctl to lumen

- Accounts & Users/best-practices-for-account-hierarchy.md
- Edge Computing Solutions/Getting Started/edge-bare-metal-billing.md
> RR edge bare metal billing 050521

- Introducing Object Storage
Lumen Edge  and URL updates to verbiage.
> 060721 introducing object storage

- Using Object Storage From 3rd Party Tools.md
Content extracted from the Object Tier Getting Started Guide per Brad Lewis and published as a separate article.
> 060521 using object storage from 3rd party tools

- Lumen Edge Private Cloud/General/glossary-of-terms.md
Changed did, and made a minor. punctuation change.
> Changed date, and minor punctuation change.

- Lumen Edge Private Cloud/General/windows-2019.md
I pushed the images in earlier pull requests.
> Made text changes to Windows 2019 article.

- Lumen Edge Private Cloud/General/faq.md
> Made text changes to this faq.

- Lumen Edge Private Cloud/Administration/adding-org-admin.md
Made text edits as advised by the SME.
> Made changes to text.

- Lumen Edge Private Cloud/Firewall/dfw-enabling.md
Slight editing change in article.
> Made slight editing change in article.

- Lumen Edge Private Cloud/General/creating-a-server.md
Made multiple image and text changes for creating a server.
> Made many image and text changes for creating a server.

- Lumen Network Storage/Getting Started/Lumen Network Storage Locations/lns-site-locations.md
ECLDE-7025 article MD text pasted into article
> Eclde 7025 add new lns site location kb

- Lumen Network Storage/Getting Started/object-tier-new-user-guide.md
ECLDE-6808 Object Storage New User Guide 005_OS-Dashboard–NoUsersAvailablelpng image name updated to 005_LNS-OTNUG_graphic.png
> updated image name

- Lumen Network Storage/Getting Started/object-storage-baas.md
Updates to article detail block
> Corrected date-author block details

- Control Portal/understang-cost estimates in control.md
> Update understang-cost estimates in control.md

- Jenkinsfile
https://ctl.atlassian.net/browse/EDGEP-90
> Adds logic to Jenkinsfile

- Support/manage-marketplace-subscriptions.md
(../images/MM#.png) had an extra ../ folder path; deleted those for five image calls, images appeared in preview
> image navigation edits

- Support/how_to_provision_solana_validator_edge_bare_metal_server.md
> Edgec 346 solana validator

- Support/how_to_provision_solana_validator_edge_bare_metal_server.md
> number format update

- Support/how_to_provision_solana_validator_edge_bare_metal_server.md
Reverts CenturyLinkCloud/PublicKB#3381
> Revert "Update Solana-Validator KB formatting / numbering"

- Control Portal/control-portal-navigation-update.md
Runner was deprecated in 2020 and is no longer available.
> Remove references to Runner

- Edge Computing Solutions/Administration/edge-orchestrator-portal-user-management.md
> Title&so-on-update
